import Foundation
import SwiftUI

// MARK: - زبان برنامه (انگلیسی پیش‌فرض؛ فارسی راست‌به‌چپ)

enum AppLanguage: String, CaseIterable, Identifiable {
    case english, persian, russian, chinese

    var id: String { rawValue }

    var label: String {
        switch self {
        case .english: return "English"
        case .persian: return "فارسی"
        case .russian: return "Русский"
        case .chinese: return "中文"
        }
    }

    var rtl: Bool { self == .persian }

    /// نام زبان برای دستورالعمل مدل‌های زبانی (پاسخ دستیار همیشه به زبان UI باشد)
    var promptLanguageName: String {
        switch self {
        case .english: return "English"
        case .persian: return "Persian (Farsi)"
        case .russian: return "Russian"
        case .chinese: return "Simplified Chinese"
        }
    }

    /// زبان ذخیره‌شده؛ پیش‌فرض انگلیسی
    static var current: AppLanguage {
        get { AppLanguage(rawValue: UserDefaults.standard.string(forKey: "appLanguage") ?? "") ?? .english }
        set { UserDefaults.standard.set(newValue.rawValue, forKey: "appLanguage") }
    }

    /// ترجمهٔ رشتهٔ انگلیسی به زبان جاری؛ کلید غایب = خود انگلیسی
    static func tr(_ en: String) -> String {
        let table: [String: String]
        switch current {
        case .english: return en
        case .persian: table = L10n.fa
        case .russian: table = L10n.ru
        case .chinese: table = L10n.zh
        }
        return table[en] ?? en
    }
}

/// فرم کوتاه برای call-siteها (thread-safe: فقط خواندن دیکشنری/UserDefaults)
enum L {
    static func tr(_ en: String) -> String { AppLanguage.tr(en) }

    /// ترجمهٔ قالب‌دار: کلید = قالب انگلیسی با `%@`/`%d`؛ مثال: L.tf("Tag: %@", name)
    static func tf(_ enFormat: String, _ args: CVarArg...) -> String {
        String(format: AppLanguage.tr(enFormat), locale: Locale(identifier: "en_US_POSIX"), arguments: args)
    }

    static var rtl: Bool { AppLanguage.current.rtl }
    static var direction: LayoutDirection { AppLanguage.current.rtl ? .rightToLeft : .leftToRight }
}

// MARK: - دیکشنری‌ها (کلید = انگلیسی)

enum L10n {
    // سطر: کلید انگلیسی → ترجمه. هر رشته‌ای که اینجا نباشد، انگلیسی نمایش داده می‌شود.
    static let fa: [String: String] = Dictionary(core.map { ($0.en, $0.fa) }, uniquingKeysWith: { _, new in new })
    static let ru: [String: String] = Dictionary(core.map { ($0.en, $0.ru) }, uniquingKeysWith: { _, new in new })
    static let zh: [String: String] = Dictionary(core.map { ($0.en, $0.zh) }, uniquingKeysWith: { _, new in new })

    struct Entry { let en: String; let fa: String; let ru: String; let zh: String }
    static let core: [Entry] = [
        // ── منوی برنامه و عمومی ──
        .init(en: "New Bookmark", fa: "نشانک جدید", ru: "Новая закладка", zh: "新建书签"),
        .init(en: "New Bookmark (⌘N)", fa: "نشانک جدید (⌘N)", ru: "Новая закладка (⌘N)", zh: "新建书签 (⌘N)"),
        .init(en: "New Folder", fa: "پوشهٔ جدید", ru: "Новая папка", zh: "新建文件夹"),
        .init(en: "New Folder (⌘⇧N)", fa: "پوشهٔ جدید (⌘⇧N)", ru: "Новая папка (⌘⇧N)", zh: "新建文件夹 (⌘⇧N)"),
        .init(en: "Quick Add", fa: "افزودن سریع", ru: "Быстрое добавление", zh: "快速添加"),
        .init(en: "Quick Add in any app", fa: "افزودن سریع در هر برنامه", ru: "Быстрое добавление в любом приложении", zh: "在任意应用中快速添加"),
        .init(en: "Chats", fa: "گفتگوها", ru: "Чаты", zh: "聊天"),
        .init(en: "Chats (⌘⇧C)", fa: "گفتگوها (⌘⇧C)", ru: "Чаты (⌘⇧C)", zh: "聊天 (⌘⇧C)"),
        .init(en: "Export HTML…", fa: "خروجی HTML…", ru: "Экспорт HTML…", zh: "导出 HTML…"),
        .init(en: "Import from Browser File…", fa: "ورودی از فایل مرورگر…", ru: "Импорт из файла браузера…", zh: "从浏览器文件导入…"),
        .init(en: "Restore Last Delete", fa: "بازگردانی آخرین حذف", ru: "Вернуть последнее удаление", zh: "撤销上次删除"),
        .init(en: "Settings…", fa: "تنظیمات…", ru: "Настройки…", zh: "设置…"),
        .init(en: "About Neshank", fa: "دربارهٔ نشانک", ru: "О программе Neshank", zh: "关于「书签」"),
        .init(en: "Cancel", fa: "لغو", ru: "Отмена", zh: "取消"),
        .init(en: "Save", fa: "ذخیره", ru: "Сохранить", zh: "保存"),
        .init(en: "Create", fa: "ساختن", ru: "Создать", zh: "创建"),
        .init(en: "Name", fa: "نام", ru: "Название", zh: "名称"),
        .init(en: "Delete", fa: "حذف", ru: "Удалить", zh: "删除"),

        // ── سایدبار ──
        .init(en: "Smart", fa: "هوشمند", ru: "Умные", zh: "智能分类"),
        .init(en: "All Bookmarks", fa: "همهٔ نشانک‌ها", ru: "Все закладки", zh: "所有书签"),
        .init(en: "Starred", fa: "ستاره‌دارها", ru: "Избранные", zh: "已加星标"),
        .init(en: "Trash", fa: "زباله‌دان", ru: "Корзина", zh: "废纸篓"),
        .init(en: "Mind Maps", fa: "نقشه‌های ذهنی", ru: "Интеллект-карты", zh: "思维导图"),
        .init(en: "Folders", fa: "پوشه‌ها", ru: "Папки", zh: "文件夹"),
        .init(en: "Unfiled", fa: "بدون پوشه", ru: "Без папки", zh: "未分类"),
        .init(en: "Bookmarks not in any folder", fa: "نشانک‌هایی که در هیچ پوشه‌ای قرار ندارند", ru: "Закладки вне папок", zh: "未归入任何文件夹的书签"),
        .init(en: "Saved Filters", fa: "فیلترهای ذخیره‌شده", ru: "Сохранённые фильтры", zh: "已存筛选器"),
        .init(en: "No saved filters yet", fa: "هنوز فیلتری ذخیره نشده", ru: "Фильтров пока нет", zh: "尚无已存筛选器"),
        .init(en: "Tags", fa: "برچسب‌ها", ru: "Теги", zh: "标签"),
        .init(en: "Tools", fa: "ابزارها", ru: "Инструменты", zh: "工具"),
        .init(en: "Mind Map Designer", fa: "طراحی نقشه ذهنی", ru: "Конструктор интеллект-карт", zh: "思维导图设计器"),
        .init(en: "Check Dead Links", fa: "بررسی لینک‌های مرده", ru: "Проверить мёртвые ссылки", zh: "检查失效链接"),
        .init(en: "Search in title, URL, tag and note…", fa: "جستجو در عنوان، آدرس، برچسب و یادداشت…", ru: "Поиск по названию, адресу, тегу и заметке…", zh: "搜索标题、网址、标签和备注…"),
        .init(en: "Search everything…", fa: "جستجو در عنوان، آدرس، برچسب و یادداشت…", ru: "Поиск по названию, адресу, тегу и заметке…", zh: "搜索标题、网址、标签和备注…"),

        // ── عملیات پوشه ──
        .init(en: "New Subfolder…", fa: "زیرپوشهٔ جدید…", ru: "Новая подпапка…", zh: "新建子文件夹…"),
        .init(en: "Rename", fa: "تغییر نام", ru: "Переименовать", zh: "重命名"),
        .init(en: "Folder Appearance…", fa: "ظاهر پوشه (رنگ و آیکون)…", ru: "Внешний вид папки…", zh: "文件夹外观…"),
        .init(en: "Add Bookmark Here", fa: "افزودن نشانک در این پوشه", ru: "Добавить закладку сюда", zh: "在此文件夹中添加书签"),
        .init(en: "Delete Folder", fa: "حذف پوشه", ru: "Удалить папку", zh: "删除文件夹"),
        .init(en: "Pin to Top", fa: "سنجاق کردن به بالا", ru: "Закрепить сверху", zh: "置顶"),
        .init(en: "Unpin", fa: "برداشتن سنجاق", ru: "Открепить", zh: "取消置顶"),
        .init(en: "Pin to Top (⌘⇧N)", fa: "پوشهٔ جدید (⌘⇧N)", ru: "Новая папка (⌘⇧N)", zh: "新建文件夹 (⌘⇧N)"),
        .init(en: "Folder will be created at the root level.", fa: "پوشه در ریشهٔ فهرست ساخته می‌شود.", ru: "Папка будет создана в корне списка.", zh: "文件夹将创建在列表根部。"),
        .init(en: "New Folder Name", fa: "نام پوشه", ru: "Название папки", zh: "文件夹名称"),
        .init(en: "Inside", fa: "داخل", ru: "Внутри", zh: "位置"),
        .init(en: "Root of List", fa: "ریشهٔ فهرست", ru: "Корень списка", zh: "列表根部"),
        .init(en: "Rename Folder", fa: "تغییر نام پوشه", ru: "Переименовать папку", zh: "重命名文件夹"),
        .init(en: "Import Browser HTML File", fa: "ورودی از فایل HTML مرورگر", ru: "Импорт HTML из браузера", zh: "从浏览器导入 HTML"),

        // ── فیلتر و برچسب ──
        .init(en: "Apply Filter", fa: "اعمال فیلتر", ru: "Применить фильтр", zh: "应用筛选器"),
        .init(en: "Delete Filter", fa: "حذف فیلتر", ru: "Удалить фильтр", zh: "删除筛选器"),
        .init(en: "Save Current Filter", fa: "ذخیرهٔ فیلتر", ru: "Сохранить фильтр", zh: "保存筛选器"),
        .init(en: "Rename Filter", fa: "تغییر نام فیلتر", ru: "Переименовать фильтр", zh: "重命名筛选器"),
        .init(en: "Remove Tag from All Bookmarks", fa: "حذف برچسب از همهٔ نشانک‌ها", ru: "Убрать тег со всех закладок", zh: "从所有书签中移除标签"),

        // ── نوار ابزار و فهرست ──
        .init(en: "New Mind Map", fa: "نقشهٔ ذهنی تازه", ru: "Новая интеллект-карта", zh: "新建思维导图"),
        .init(en: "View", fa: "نمایش", ru: "Вид", zh: "视图"),
        .init(en: "List View Mode", fa: "حالت نمایش فهرست", ru: "Режим списка", zh: "列表视图模式"),
        .init(en: "Settings (⌘,)", fa: "تنظیمات (⌘,)", ru: "Настройки (⌘,)", zh: "设置 (⌘,)"),
        .init(en: "Open Settings", fa: "باز کردن تنظیمات", ru: "Открыть настройки", zh: "打开设置"),
        .init(en: "Sort", fa: "مرتب‌سازی", ru: "Сортировка", zh: "排序"),
        .init(en: "Grouping", fa: "گروه‌بندی", ru: "Группировка", zh: "分组"),
        .init(en: "More", fa: "بیشتر", ru: "Ещё", zh: "更多"),
        .init(en: "Search", fa: "جستجو", ru: "Поиск", zh: "搜索"),
        .init(en: "No bookmarks here", fa: "هنوز نشانکی اینجا نیست", ru: "Здесь пока нет закладок", zh: "这里还没有书签"),
        .init(en: "Press ⌘N to add your first bookmark.", fa: "با ⌘N اولین نشانک خود را اضافه کنید.", ru: "Нажмите ⌘N, чтобы добавить первую закладку.", zh: "按 ⌘N 添加第一个书签。"),
        .init(en: "Open", fa: "باز کردن", ru: "Открыть", zh: "打开"),
        .init(en: "Copy URL", fa: "کپی آدرس", ru: "Копировать адрес", zh: "复制网址"),
        .init(en: "Edit…", fa: "ویرایش…", ru: "Изменить…", zh: "编辑…"),
        .init(en: "Remove from Folder", fa: "حذف از پوشه", ru: "Убрать из папки", zh: "移出文件夹"),
        .init(en: "Delete (Move to Trash)", fa: "حذف (رفتن به زباله‌دان)", ru: "Удалить (в корзину)", zh: "删除（移到废纸篓）"),
        .init(en: "Restore from Trash", fa: "بازگردانی از زباله‌دان", ru: "Восстановить из корзины", zh: "从废纸篓恢复"),
        .init(en: "Delete Permanently", fa: "حذف قطعی", ru: "Удалить навсегда", zh: "永久删除"),
        .init(en: "Star", fa: "ستاره‌دار کردن", ru: "В избранное", zh: "加星标"),
        .init(en: "Remove Star", fa: "حذف ستاره", ru: "Убрать из избранного", zh: "取消星标"),
        .init(en: "Folder", fa: "پوشه", ru: "Папка", zh: "文件夹"),
        .init(en: "Tag", fa: "برچسب", ru: "Тег", zh: "标签"),
        .init(en: "New Tag…", fa: "برچسب جدید…", ru: "Новый тег…", zh: "新标签…"),
        .init(en: "Mark All as Read", fa: "خوانده", ru: "Прочитано", zh: "标为已读"),

        // ── پنل جزئیات ──
        .init(en: "Note", fa: "یادداشت", ru: "Заметка", zh: "备注"),
        .init(en: "Add Tag", fa: "افزودن برچسب", ru: "Добавить тег", zh: "添加标签"),
        .init(en: "This bookmark is in the Trash", fa: "این نشانک در زباله‌دان است", ru: "Эта закладка в корзине", zh: "此书签在废纸篓中"),
        .init(en: "Restore", fa: "بازگردانی", ru: "Восстановить", zh: "恢复"),
        .init(en: "Preview is only available for web pages", fa: "پیش‌نمایش فقط برای صفحات وب در دسترس است", ru: "Предпросмотр доступен только для веб-страниц", zh: "预览仅适用于网页"),
        .init(en: "Capture Page Screenshot", fa: "گرفتن عکس صفحه", ru: "Снимок страницы", zh: "截取页面截图"),
        .init(en: "Select a bookmark from the list", fa: "نشانکی را از فهرست انتخاب کنید", ru: "Выберите закладку из списка", zh: "从列表中选择书签"),
        .init(en: "Mind Map", fa: "نقشهٔ ذهنی", ru: "Интеллект-карта", zh: "思维导图"),
        .init(en: "Show Saved Mind Map", fa: "نمایش نقشهٔ ذهنی ذخیره‌شده", ru: "Показать сохранённую карту", zh: "显示已存思维导图"),
        .init(en: "Mind Map about Selected Bookmark", fa: "نقشهٔ ذهنی دربارهٔ نشانک انتخاب‌شده", ru: "Карта по выбранной закладке", zh: "为所选书签生成思维导图"),

        // ── تنظیمات ──
        .init(en: "General", fa: "عمومی", ru: "Общие", zh: "通用"),
        .init(en: "AI Assistant", fa: "دستیار هوشمند", ru: "ИИ-ассистент", zh: "AI 助手"),
        .init(en: "Appearance", fa: "ظاهر", ru: "Оформление", zh: "外观"),
        .init(en: "Text Archive", fa: "آرشیو متن", ru: "Архив текста", zh: "文本存档"),
        .init(en: "Data", fa: "داده‌ها", ru: "Данные", zh: "数据"),
        .init(en: "Statistics", fa: "آمار", ru: "Статистика", zh: "统计"),
        .init(en: "About", fa: "درباره", ru: "О программе", zh: "关于"),
        .init(en: "Check links automatically on launch", fa: "بررسی خودکار لینک‌ها هنگام اجرا", ru: "Проверять ссылки при запуске", zh: "启动时自动检查链接"),
        .init(en: "Auto-fetch title, description and image when adding", fa: "دریافت خودکار عنوان، توضیح و تصویر هنگام افزودن", ru: "Автоматически получать заголовок и изображение", zh: "添加时自动获取标题、描述和图片"),
        .init(en: "Default View Mode", fa: "حالت نمایش پیش‌فرض", ru: "Режим списка по умолчанию", zh: "默认视图模式"),
        .init(en: "Quick Add Shortcut", fa: "میان‌بر افزودن سریع", ru: "Горячая клавиша быстрого добавления", zh: "快速添加快捷键"),
        .init(en: "App Language", fa: "زبان برنامه", ru: "Язык приложения", zh: "应用语言"),
        .init(en: "Archive full page text when adding", fa: "ذخیرهٔ نسخهٔ کامل صفحه (متن) هنگام افزودن", ru: "Сохранять полный текст страницы при добавлении", zh: "添加时保存完整网页文本"),
        .init(en: "Capture real page screenshots for cards", fa: "گرفتن عکس واقعی صفحه برای کارت‌ها", ru: "Делать снимки страниц для карточек", zh: "为卡片截取真实页面截图"),
        .init(en: "Database", fa: "پایگاه داده", ru: "База данных", zh: "数据库"),
        .init(en: "Show in Finder", fa: "نمایش در Finder", ru: "Показать в Finder", zh: "在 Finder 中显示"),
        .init(en: "Import from Browser…", fa: "ورودی از فایل مرورگر…", ru: "Импорт из браузера…", zh: "从浏览器导入…"),
        .init(en: "Find & Remove Duplicates…", fa: "یافتن و حذف تکراری‌ها…", ru: "Найти дубликаты…", zh: "查找并删除重复项…"),
        .init(en: "Empty Trash", fa: "خالی کردن زباله‌دان", ru: "Очистить корзину", zh: "清空废纸篓"),
        .init(en: "Check All Links", fa: "بررسی همهٔ لینک‌ها", ru: "Проверить все ссылки", zh: "检查所有链接"),
        .init(en: "Delete Dead Bookmarks", fa: "حذف نشانک‌های مرده", ru: "Удалить мёртвые закладки", zh: "删除失效书签"),
        .init(en: "Assistant API Key", fa: "کلید دستیار", ru: "Ключ ассистента", zh: "助手 API 密钥"),
        .init(en: "My Profile", fa: "پروفایل من", ru: "Мой профиль", zh: "我的画像"),
        .init(en: "Test Connection", fa: "تست اتصال", ru: "Проверить соединение", zh: "测试连接"),
        .init(en: "Model Selection Mode", fa: "حالت انتخاب مدل", ru: "Режим выбора модели", zh: "模型选择方式"),
        .init(en: "From Provider List", fa: "از فهرست سرویس", ru: "Из списка сервиса", zh: "从服务列表选择"),
        .init(en: "Manual Entry", fa: "ورود دستی", ru: "Вручную", zh: "手动输入"),
        .init(en: "Test This Model", fa: "آزمودن این مدل", ru: "Проверить эту модель", zh: "测试此模型"),
        .init(en: "Light Mode", fa: "حالت روشنایی", ru: "Оформление", zh: "外观模式"),
        .init(en: "App Color", fa: "رنگ برنامه", ru: "Цвет приложения", zh: "应用颜色"),
        .init(en: "List Density", fa: "چگالی فهرست", ru: "Плотность списка", zh: "列表密度"),
        .init(en: "Default", fa: "پیش‌فرض", ru: "Системный", zh: "默认"),

        // ── ویرایشگر و افزودن سریع ──
        .init(en: "New Bookmark Editor", fa: "نشانک تازه", ru: "Новая закладка", zh: "新书签"),
        .init(en: "Edit Bookmark", fa: "ویرایش نشانک", ru: "Изменить закладку", zh: "编辑书签"),
        .init(en: "Title", fa: "عنوان", ru: "Заголовок", zh: "标题"),
        .init(en: "URL", fa: "آدرس", ru: "Адрес", zh: "网址"),

        // ── پالت فرمان و پنل‌ها ──
        .init(en: "Search command…", fa: "جستجوی فرمان…", ru: "Поиск команды…", zh: "搜索命令…"),
        .init(en: "Ask the library…", fa: "پرسش از کتابخانه…", ru: "Спросить библиотеку…", zh: "询问书签库…"),
        .init(en: "Ask the whole library", fa: "پرسش از کل کتابخانه", ru: "Спросить всю библиотеку", zh: "询问整个书签库"),
        .init(en: "New Library Chat", fa: "گفتگوی تازه", ru: "Новый чат", zh: "新建聊天"),
        .init(en: "All previous chats", fa: "همهٔ چت‌های قبلی", ru: "Все предыдущие чаты", zh: "所有历史聊天"),
        .init(en: "Quick Add Panel", fa: "پنل افزودن سریع", ru: "Панель быстрого добавления", zh: "快速添加面板"),
        .init(en: "Menu Bar Panel", fa: "پنل نوار منو", ru: "Панель строки меню", zh: "菜单栏面板"),
        .init(en: "Neshank Window", fa: "پنجرهٔ نشانک", ru: "Окно Neshank", zh: "书签窗口"),

        // ── درباره ──
        .init(en: "Neshank — native macOS bookmark manager, built with SwiftUI and SQLite.",
              fa: "نشانک — مدیر نشانک بومی مک، ساخته‌شده با SwiftUI و SQLite.",
              ru: "Neshank — нативный менеджер закладок для macOS на SwiftUI и SQLite.",
              zh: "书签 — 使用 SwiftUI 与 SQLite 构建的原生 macOS 书签管理器。"),
        .init(en: "Made by hosein shahraki", fa: "ساخت hosein shahraki",
              ru: "Создано hosein shahraki", zh: "由 hosein shahraki 制作"),
        // ── کلیدهای افزودنی بومی‌سازی کامل رابط (کلید = انگلیسی) ──
        .init(en: "Filter Name", fa: "نام فیلتر", ru: "Название фильтра", zh: "筛选器名称"),
        .init(en: "Empty Trash?", fa: "زباله‌دان خالی شود؟", ru: "Очистить корзину?", zh: "清空废纸篓？"),
        .init(en: "Delete All Permanently", fa: "حذف قطعی همه", ru: "Удалить всё навсегда", zh: "全部永久删除"),
        .init(en: "%@ bookmarks will be permanently deleted.", fa: "%@ نشانک برای همیشه حذف می‌شود.", ru: "%@ закладок будет удалено навсегда.", zh: "将永久删除 %@ 个书签。"),
        .init(en: "%@ bookmarks selected", fa: "%@ نشانک انتخاب شده", ru: "Выбрано закладок: %@", zh: "已选择 %@ 个书签"),
        .init(en: "Clear Selection", fa: "لغو انتخاب", ru: "Снять выделение", zh: "取消选择"),
        .init(en: "Add Tag to Selected Bookmarks", fa: "افزودن برچسب به نشانک‌های انتخاب‌شده", ru: "Добавить тег выбранным закладкам", zh: "为所选书签添加标签"),
        .init(en: "Tag Name", fa: "نام برچسب", ru: "Название тега", zh: "标签名称"),
        .init(en: "Add", fa: "افزودن", ru: "Добавить", zh: "添加"),
        .init(en: "Search mind maps by name, URL or text…", fa: "جستجو در نام، آدرس یا متن نقشه…", ru: "Поиск карт по названию, адресу или тексту…", zh: "按名称、网址或内容搜索思维导图…"),
        .init(en: "Clear Search", fa: "پاک کردن جستجو", ru: "Очистить поиск", zh: "清除搜索"),
        .init(en: "New Map", fa: "نقشهٔ تازه", ru: "Новая карта", zh: "新建导图"),
        .init(en: "Create New Mind Map", fa: "ساخت نقشهٔ ذهنی تازه", ru: "Создать интеллект-карту", zh: "新建思维导图"),
        .init(en: "Open Mind Map", fa: "باز کردن نقشه", ru: "Открыть интеллект-карту", zh: "打开思维导图"),
        .init(en: "Open Source Page", fa: "باز کردن صفحهٔ مبدأ", ru: "Открыть исходную страницу", zh: "打开来源网页"),
        .init(en: "Delete Mind Map", fa: "حذف نقشه", ru: "Удалить интеллект-карту", zh: "删除思维导图"),
        .init(en: "No mind maps saved yet", fa: "هنوز نقشهٔ ذهنی ذخیره نشده", ru: "Сохранённых интеллект-карт пока нет", zh: "尚未保存思维导图"),
        .init(en: "No mind maps found", fa: "نقشه‌ای پیدا نشد", ru: "Интеллект-карты не найдены", zh: "未找到思维导图"),
        .init(en: "Select a bookmark and create a map from Tools → Mind Map Designer. Each map is saved separately in this list.", fa: "یک نشانک را انتخاب کنید و از «ابزارها ← طراحی نقشه ذهنی» نقشه بسازید. هر نقشه جداگانه در این فهرست ذخیره می‌شود.", ru: "Выберите закладку и создайте карту через «Инструменты → Конструктор интеллект-карт». Каждая карта сохраняется в этом списке отдельно.", zh: "请选择一个书签，然后通过“工具 → 思维导图设计器”创建导图。每张导图都会单独保存在此列表中。"),
        .init(en: "Search by map title, URL or text.", fa: "عنوان، آدرس یا متن نقشه را جستجو کنید.", ru: "Выполните поиск по названию, адресу или тексту карты.", zh: "请按导图标题、网址或内容搜索。"),
        .init(en: "Design New Mind Map", fa: "طراحی نقشهٔ تازه", ru: "Создать карту в конструкторе", zh: "设计新思维导图"),
        .init(en: "%@ mind maps selected", fa: "%@ نقشه انتخاب شد", ru: "Выбрано интеллект-карт: %@", zh: "已选择 %@ 张思维导图"),
        .init(en: "Deletes selected mind maps; source bookmarks are kept", fa: "حذف نقشه‌های انتخاب‌شده؛ نشانک‌های مبدأ حذف نمی‌شوند", ru: "Удаляет выбранные интеллект-карты; исходные закладки сохраняются", zh: "删除所选思维导图；不会删除来源书签"),
        .init(en: "No results found", fa: "نتیجه‌ای پیدا نشد", ru: "Ничего не найдено", zh: "未找到结果"),
        .init(en: "Try different words or type a domain.", fa: "عبارت دیگری امتحان کنید یا دامنه را بنویسید.", ru: "Попробуйте изменить запрос или введите домен.", zh: "请尝试其他关键词，或输入域名。"),
        .init(en: "List view mode: %@", fa: "حالت نمایش فهرست: %@", ru: "Режим списка: %@", zh: "列表视图模式：%@"),
        .init(en: "Save Current Filter…", fa: "ذخیرهٔ فیلتر فعلی…", ru: "Сохранить текущий фильтр…", zh: "保存当前筛选器…"),
        .init(en: "Restore All", fa: "بازگردانی همه", ru: "Восстановить все", zh: "全部恢复"),
        .init(en: "Checking…", fa: "در حال بررسی…", ru: "Проверка…", zh: "正在检查…"),
        .init(en: "Grouping, sorting and tools", fa: "گروه‌بندی، مرتب‌سازی و ابزارها", ru: "Группировка, сортировка и инструменты", zh: "分组、排序和工具"),
        .init(en: "Tag: %@", fa: "برچسب: %@", ru: "Тег: %@", zh: "标签：%@。"),
        .init(en: "%@ nodes", fa: "%@ گره", ru: "%@ узлов", zh: "%@ 个节点"),
        .init(en: "This link appears to be dead", fa: "این لینک مرده به نظر می‌رسد", ru: "Похоже, эта ссылка не работает", zh: "此链接似乎已失效"),
        .init(en: "Add to Folder…", fa: "افزودن به پوشه…", ru: "Добавить в папку…", zh: "添加到文件夹…"),
        .init(en: "Close Map Details", fa: "بستن جزئیات نقشه", ru: "Закрыть сведения о карте", zh: "关闭导图详情"),
        .init(en: "Zoom Out", fa: "کوچک‌نمایی", ru: "Уменьшить", zh: "缩小"),
        .init(en: "Zoom In", fa: "بزرگ‌نمایی", ru: "Увеличить", zh: "放大"),
        .init(en: "Fit to Window", fa: "اندازهٔ مناسب", ru: "По размеру окна", zh: "适应窗口"),
        .init(en: "Expand All", fa: "باز کردن همه", ru: "Развернуть все", zh: "全部展开"),
        .init(en: "Collapse All", fa: "بستن همه", ru: "Свернуть все", zh: "全部折叠"),
        .init(en: "Add Child Node", fa: "افزودن گره به انتخاب‌شده", ru: "Добавить дочерний узел", zh: "添加子节点"),
        .init(en: "Delete Selected Node", fa: "حذف گرهٔ انتخاب‌شده", ru: "Удалить выбранный узел", zh: "删除所选节点"),
        .init(en: "JSON File", fa: "فایل JSON", ru: "Файл JSON", zh: "JSON 文件"),
        .init(en: "Markdown File", fa: "فایل مارک‌داون", ru: "Файл Markdown", zh: "Markdown 文件"),
        .init(en: "PNG Image", fa: "تصویر PNG", ru: "Изображение PNG", zh: "PNG 图片"),
        .init(en: "JPEG Image", fa: "تصویر JPEG", ru: "Изображение JPEG", zh: "JPEG 图片"),
        .init(en: "Standalone HTML Page", fa: "صفحهٔ HTML مستقل", ru: "Автономная HTML-страница", zh: "独立 HTML 页面"),
        .init(en: "Export", fa: "خروجی", ru: "Экспорт", zh: "导出"),
        .init(en: "Export map (JSON, Markdown, image, HTML)", fa: "خروجی گرفتن از نقشه (JSON، مارک‌داون، تصویر، HTML)", ru: "Экспорт карты (JSON, Markdown, изображение, HTML)", zh: "导出导图（JSON、Markdown、图片、HTML）"),
        .init(en: "Search in nodes", fa: "جستجو در گره‌ها", ru: "Поиск по узлам", zh: "在节点中搜索"),
        .init(en: "Open Map", fa: "باز کردن نقشه", ru: "Открыть карту", zh: "打开导图"),
        .init(en: "View and edit the saved mind map", fa: "نمایش و ویرایش نقشهٔ ذخیره‌شده", ru: "Показать и отредактировать сохранённую карту", zh: "查看并编辑已保存的思维导图"),
        .init(en: "New Map from This Page", fa: "نقشهٔ تازه از همین صفحه", ru: "Новая карта по этой странице", zh: "从此页面新建导图"),
        .init(en: "Saves as a separate record; the previous map is kept", fa: "نقشهٔ جدید به‌عنوان رکورد جدا ذخیره می‌شود؛ نقشهٔ قبلی باقی می‌ماند", ru: "Сохраняется как отдельная запись; прежняя карта остаётся", zh: "会另存为独立记录；原导图保留"),
        .init(en: "Delete Map", fa: "حذف نقشه", ru: "Удалить карту", zh: "删除导图"),
        .init(en: "Deletes only this map; the bookmark stays untouched", fa: "فقط همین نقشه حذف می‌شود؛ نشانک اصلی دست‌نخورده می‌ماند", ru: "Удаляется только эта карта; закладка остаётся без изменений", zh: "只删除此导图；原书签不受影响"),
        .init(en: "JSON export saved", fa: "خروجی JSON ذخیره شد", ru: "Экспорт JSON сохранён", zh: "已保存 JSON 导出"),
        .init(en: "Markdown export saved", fa: "خروجی مارک‌داون ذخیره شد", ru: "Экспорт Markdown сохранён", zh: "已保存 Markdown 导出"),
        .init(en: "Image %@ saved", fa: "تصویر %@ ذخیره شد", ru: "Изображение %@ сохранено", zh: "已保存 %@ 图片"),
        .init(en: "Standalone HTML page saved", fa: "صفحهٔ HTML مستقل ذخیره شد", ru: "Автономная HTML-страница сохранена", zh: "已保存独立 HTML 页面"),
        .init(en: "Move this bookmark to Trash?", fa: "این نشانک به زباله‌دان برود؟", ru: "Переместить эту закладку в корзину?", zh: "将此书签移入废纸篓？"),
        .init(en: "Move to Trash", fa: "انتقال به زباله‌دان", ru: "Переместить в корзину", zh: "移入废纸篓"),
        .init(en: "You can undo with ⌘Z.", fa: "با ⌘Z می‌توانید برش گردانید.", ru: "Можно отменить нажатием ⌘Z.", zh: "可用 ⌘Z 撤销。"),
        .init(en: "Delete this bookmark permanently?", fa: "این نشانک برای همیشه حذف شود؟", ru: "Удалить эту закладку навсегда?", zh: "永久删除此书签？"),
        .init(en: "Also erased from the Trash; this cannot be undone.", fa: "از زباله‌دان هم پاک می‌شود و برگشتی ندارد.", ru: "Также стирается из корзины; это действие необратимо.", zh: "也会从废纸篓中清除，无法恢复。"),
        .init(en: "Unread", fa: "نخوانده", ru: "Непрочитано", zh: "未读"),
        .init(en: "Archived", fa: "بایگانی", ru: "В архиве", zh: "已归档"),
        .init(en: "Assistant: is this page useful for me? (⌘⇧D)", fa: "دستیار: آیا این صفحه به درد من می‌خورد؟ (⌘⇧D)", ru: "Ассистент: пригодится ли мне эта страница? (⌘⇧D)", zh: "助手：这个页面对我有用吗？(⌘⇧D)"),
        .init(en: "Toggle Star", fa: "ستاره‌دار", ru: "В избранном", zh: "星标"),
        .init(en: "Ask the Assistant…", fa: "پرسش از دستیار…", ru: "Спросить ассистента…", zh: "询问助手…"),
        .init(en: "Recheck", fa: "دوباره بررسی کن", ru: "Проверить снова", zh: "重新检查"),
        .init(en: "Close Panel", fa: "بستن پنل", ru: "Закрыть панель", zh: "关闭面板"),
        .init(en: "Close Details Panel", fa: "بستن پنل جزئیات", ru: "Закрыть панель сведений", zh: "关闭详情面板"),
        .init(en: "Open in Browser", fa: "باز کردن در مرورگر", ru: "Открыть в браузере", zh: "在浏览器中打开"),
        .init(en: "Write your note…", fa: "یادداشت خود را بنویسید…", ru: "Запишите заметку…", zh: "写下你的备注…"),
        .init(en: "Captures a real screenshot of the page and shows it on cards", fa: "عکس واقعی صفحه را می‌گیرد و در کارت‌ها نمایش می‌دهد", ru: "Делает настоящий снимок страницы и показывает его на карточках", zh: "截取页面真实截图并显示在卡片上"),
        .init(en: "In Trash since %@", fa: "از %@", ru: "В корзине с %@", zh: "自 %@ 起在废纸篓中"),
        .init(en: "Added: %@", fa: "افزوده شد: %@", ru: "Добавлено: %@", zh: "添加于：%@"),
        .init(en: "Last checked: %@", fa: "آخرین بررسی: %@", ru: "Последняя проверка: %@", zh: "上次检查：%@"),
        .init(en: "Delete this chat and all its messages?", fa: "این گفتگو و همهٔ پیام‌هایش حذف شود؟", ru: "Удалить этот чат и все его сообщения?", zh: "删除此聊天及其所有消息？"),
        .init(en: "Delete Chat", fa: "حذف گفتگو", ru: "Удалить чат", zh: "删除聊天"),
        .init(en: "Clear all messages in this chat? (The chat is kept)", fa: "همهٔ پیام‌های این گفتگو پاک شود؟ (گفتگو می‌ماند)", ru: "Очистить все сообщения этого чата? (Чат останется)", zh: "清除此聊天的全部消息？（聊天保留）"),
        .init(en: "Start Fresh", fa: "شروع از نو", ru: "Начать заново", zh: "重新开始"),
        .init(en: "Delete all chats?", fa: "همهٔ گفتگوها حذف شوند؟", ru: "Удалить все чаты?", zh: "删除所有聊天？"),
        .init(en: "Delete All", fa: "حذف همه", ru: "Удалить все", zh: "全部删除"),
        .init(en: "About Selected Bookmark", fa: "دربارهٔ نشانک انتخاب‌شده", ru: "О выбранной закладке", zh: "关于所选书签"),
        .init(en: "Search chats…", fa: "جستجو در گفتگوها…", ru: "Поиск по чатам…", zh: "搜索聊天…"),
        .init(en: "No chats yet", fa: "هنوز گفتگویی ندارید", ru: "Пока нет чатов", zh: "还没有聊天"),
        .init(en: "No chats found", fa: "گفتگویی پیدا نشد", ru: "Чаты не найдены", zh: "未找到聊天"),
        .init(en: "Close", fa: "بستن", ru: "Закрыть", zh: "关闭"),
        .init(en: "Bookmark", fa: "نشانک", ru: "Закладка", zh: "书签"),
        .init(en: "Ask the Library", fa: "پرسش از کتابخانه", ru: "Спросить библиотеку", zh: "询问书签库"),
        .init(en: "%@ messages", fa: "%@ پیام", ru: "%@ сообщений", zh: "%@ 条消息"),
        .init(en: "Continue", fa: "ادامه", ru: "Продолжить", zh: "继续"),
        .init(en: "Rename…", fa: "تغییر نام…", ru: "Переименовать…", zh: "重命名…"),
        .init(en: "Pin", fa: "سنجاق‌کردن", ru: "Закрепить", zh: "置顶"),
        .init(en: "Start Fresh (Clear Messages)", fa: "شروع از نو (پاک‌کردن پیام‌ها)", ru: "Начать заново (очистить сообщения)", zh: "重新开始（清除消息）"),
        .init(en: "Chat Name", fa: "نام گفتگو", ru: "Название чата", zh: "聊天名称"),
        .init(en: "Show this bookmark in the main window", fa: "نمایش این نشانک در پنجرهٔ اصلی", ru: "Показать эту закладку в главном окне", zh: "在主窗口中显示此书签"),
        .init(en: "No Chat Selected", fa: "گفتگویی انتخاب نشده", ru: "Чат не выбран", zh: "未选择聊天"),
        .init(en: "Close (Esc)", fa: "بستن (Esc)", ru: "Закрыть (Esc)", zh: "关闭 (Esc)"),
        .init(en: "Assistant is typing…", fa: "دستیار در حال نوشتن…", ru: "Ассистент печатает…", zh: "助手正在输入…"),
        .init(en: "Ask the Entire Library", fa: "از کل کتابخانه بپرس", ru: "Спросите всю библиотеку", zh: "询问整个书签库"),
        .init(en: "For example: “What have I saved about resin safety?” — answers cite the matching bookmarks.", fa: "مثلاً: «چه چیزی دربارهٔ ایمنی رزین ذخیره کرده‌ام؟» — پاسخ با ارجاع به همان نشانک‌ها داده می‌شود.", ru: "Например: «Что я сохранял о безопасности смол?» — ответ со ссылками на эти закладки.", zh: "例如：“我保存了哪些关于树脂安全的内容？”——回答会引用相关书签。"),
        .init(en: "Tap a quick question or type your own; the chat is saved and you can continue it anytime.", fa: "یکی از پرسش‌های سریع را بزن یا پرسش خودت را بنویس؛ گفتگو ذخیره می‌شود و هر وقت خواستی ادامه‌اش می‌دهی.", ru: "Нажмите на быстрый вопрос или введите свой; чат сохраняется, и его можно продолжить в любое время.", zh: "点击快捷问题或输入你自己的问题；聊天会保存，随时可以继续。"),
        .init(en: "Select a chat from the list or start a new one.", fa: "یک گفتگو از فهرست کنار انتخاب کن یا گفتگوی تازه بساز.", ru: "Выберите чат из списка или создайте новый.", zh: "从旁边的列表中选择一个聊天，或新建一个聊天。"),
        .init(en: "What do I have on safety and ventilation?", fa: "چه چیزهایی دربارهٔ ایمنی و تهویه دارم؟", ru: "Что у меня есть о безопасности и вентиляции?", zh: "我有哪些关于安全与通风的收藏？"),
        .init(en: "Which bookmarks should I revisit before buying?", fa: "کدام نشانک‌ها را برای خرید باید دوباره ببینم؟", ru: "Какие закладки стоит пересмотреть перед покупкой?", zh: "购买前应该重看哪些书签？"),
        .init(en: "What topic have I saved the most?", fa: "چه موضوعی را بیشتر از همه ذخیره کرده‌ام؟", ru: "Какую тему я сохранял чаще всего?", zh: "我保存最多的话题是什么？"),
        .init(en: "Sources", fa: "منابع", ru: "Источники", zh: "来源"),
        .init(en: "Show “%@” in the main window", fa: "نمایش «%@» در پنجرهٔ اصلی", ru: "Показать «%@» в главном окне", zh: "在主窗口中显示「%@」"),
        .init(en: "Ask your library… (e.g. what do I have about resin?)", fa: "از کتابخانه‌ات بپرس… (مثلاً: چه چیزی دربارهٔ رزین دارم؟)", ru: "Спросите свою библиотеку… (например: что у меня о смоле?)", zh: "询问你的书签库…（例如：我有哪些关于树脂的内容？）"),
        .init(en: "Type your question…", fa: "پرسشت را بنویس…", ru: "Введите свой вопрос…", zh: "输入你的问题…"),
        .init(en: "Send", fa: "ارسال", ru: "Отправить", zh: "发送"),
        .init(en: "Answers are based on your own bookmarks, with sources listed below the reply.", fa: "پاسخ بر پایهٔ نشانک‌های خودت داده می‌شود و منابع زیر پاسخ فهرست می‌شوند.", ru: "Ответ строится на ваших закладках; источники перечислены под ответом.", zh: "回答基于你自己的书签，来源会列在回答下方。"),
        .init(en: "This chat is saved; continue it later from this page.", fa: "این گفتگو ذخیره می‌شود؛ بعداً از همین صفحه ادامه‌اش بده.", ru: "Этот чат сохраняется; продолжите его позже с этой страницы.", zh: "此聊天会保存；之后可从此页面继续。"),
        .init(en: "To get started, create a new chat.", fa: "برای شروع، یک گفتگوی تازه بساز.", ru: "Для начала создайте новый чат.", zh: "开始前请先新建一个聊天。"),
        .init(en: "Yesterday", fa: "دیروز", ru: "Вчера", zh: "昨天"),
        .init(en: "Save current filter (search + scope + sort)", fa: "ذخیرهٔ فیلتر فعلی (جستجو + محدوده + مرتب‌سازی)", ru: "Сохранить текущий фильтр (поиск + область + сортировка)", zh: "保存当前筛选器（搜索＋范围＋排序）"),
        .init(en: "The current search, scope and sort will be saved with this name.", fa: "جستجو، محدوده و مرتب‌سازی فعلی با این نام ذخیره می‌شود.", ru: "Текущий поиск, область و сортировка будут сохранены под этим именем.", zh: "当前的搜索、范围和排序将以此名称保存。"),
        .init(en: "A subfolder of “%@” will be created.", fa: "زیرپوشه‌ای از «%@» ساخته می‌شود.", ru: "Будет создана подпапка «%@».", zh: "将在“%@”下创建子文件夹。"),
        .init(en: "Collapse Subfolders", fa: "بستن زیرپوشه‌ها", ru: "Свернуть подпапки", zh: "收起子文件夹"),
        .init(en: "Show Subfolders", fa: "نمایش زیرپوشه‌ها", ru: "Показать подпاپки", zh: "显示子文件夹"),
        .init(en: "Expand Subfolders", fa: "باز کردن زیرپوشه‌ها", ru: "Развернуть подпапки", zh: "展开子文件夹"),
        .init(en: "Separate window: turn a web page into a mind map", fa: "پنجرهٔ جداگانه: تبدیل یک صفحهٔ وب به نقشهٔ ذهنی", ru: "Отдельное окно: превратить веб-страницу в интеллект-карту", zh: "独立窗口：将网页转换为思维导图"),
        .init(en: "Drop the link here", fa: "لینک را اینجا رها کنید", ru: "Перетащите ссылку сюда", zh: "将链接拖放到此处"),
        .init(en: "The Quick Add form will open with the address filled in", fa: "فرم «افزودن سریع» با آدرس پر می‌شود", ru: "Форма быстрого добавления откроется с заполненным адресом", zh: "快速添加表单将自动填入网址"),
        .init(en: "Drag to resize (double-click to reset to default size)", fa: "برای تغییر عرض بکشید (دوبار کلیک = بازگشت به اندازهٔ پیش‌فرض)", ru: "Потяните, чтобы изменить ширину (двойной клик — сброс до размера по умолчанию)", zh: "拖动以调整宽度（双击恢复默认宽度）"),
        .init(en: "Pinned", fa: "سنجاق‌شده", ru: "Закреплено", zh: "已置顶"),
        .init(en: "Opens the Quick Add panel when pressed in any app — no system permission needed.", fa: "در هر برنامه‌ای فشرده شود، پنل «افزودن سریع» باز می‌شود — بدون نیاز به مجوز سیستم.", ru: "Открывает панель быстрого добавления при нажатии в любом приложении — системные разрешения не нужны.", zh: "在任意应用中按下即可打开「快速添加」面板 — 无需系统权限。"),
        .init(en: "Base URL (OpenAI-compatible)", fa: "آدرس پایهٔ سرویس (سازگار با OpenAI)", ru: "Базовый URL (совместимый с OpenAI)", zh: "服务基础地址（兼容 OpenAI）"),
        .init(en: "Example: https://opencode.ai/zen/go/v1 or https://api.openai.com/v1 — /chat/completions and /models are added automatically.", fa: "مثال: https://opencode.ai/zen/go/v1 یا https://api.openai.com/v1 — پسوند /chat/completions و /models خودکار اضافه می‌شود.", ru: "Пример: https://opencode.ai/zen/go/v1 или https://api.openai.com/v1 — суффиксы /chat/completions и /models добавляются автоматически.", zh: "示例：https://opencode.ai/zen/go/v1 或 https://api.openai.com/v1 — 会自动追加 /chat/completions 与 /models 后缀。"),
        .init(en: "Model", fa: "مدل", ru: "Модель", zh: "模型"),
        .init(en: "Fetch model list from provider", fa: "دریافت فهرست مدل‌ها از سرویس", ru: "Получить список моделей от провайдера", zh: "从服务提供商获取模型列表"),
        .init(en: "Sends a small request for this model only — checks compatibility with the chat protocol", fa: "یک درخواست کوچک فقط برای همین مدل — بررسی سازگاری با پروتکل گفتگو", ru: "Отправляет небольшой запрос только для этой модели — проверка совместимости с протоколом чата", zh: "仅针对此模型发送一个小请求 — 检查对话协议兼容性"),
        .init(en: "%@ models fetched from the provider and kept between launches. Some models may not support the chat protocol — verify with “Test This Model”.", fa: "%@ مدل از سرویس گرفته شد و بین اجراها نگه داشته می‌شود. برخی مدل‌ها ممکن است با پروتکل گفتگو سازگار نباشد — با «آزمودن این مدل» مطمئن شوید.", ru: "Получено %@ моделей от провайдера; список сохраняется между запусками. Некоторые модели могут не поддерживать протокол чата — проверьте с помощью «Проверить эту модель».", zh: "已从服务获取 %@ 个模型并跨启动保留。部分模型可能不支持对话协议 — 请用「测试此模型」确认。"),
        .init(en: "Model name (e.g. deepseek-v4.1-flash)", fa: "نام مدل (مثلاً deepseek-v4.1-flash)", ru: "Название модели (например deepseek-v4.1-flash)", zh: "模型名称（例如 deepseek-v4.1-flash）"),
        .init(en: "Write who you are, what you look for, your budget and technical level — e.g. “I'm a UI designer; budget up to 2M tomans; looking for a color-accurate monitor for the office”. The assistant weighs answers against this.", fa: "چه کسی هستید، دنبال چه می‌گردید، بودجه و سطح فنی‌تان را بنویسید — مثلاً: «طراح رابط کاربری‌ام؛ بودجه تا ۲ میلیون تومان؛ دنبال مانیتور رنگ‌دقیق برای دفتر». دستیار پاسخ را با همین می‌سنجد.", ru: "Напишите, кто вы, что ищете, свой бюджет и технический уровень — например: «Я UI-дизайнер; бюджет до 2 млн туманов; ищу цветоточный монитор для офиса». Ассистент оценивает ответы по этому профилю.", zh: "写下你是谁、在找什么、预算和技术水平 — 例如：「我是界面设计师；预算 200 万土曼；为办公室找一台色彩精准的显示器」。助手会据此衡量回答。"),
        .init(en: "The Sparkle (✦) button or ⌘⇧D on the selected bookmark opens the assistant panel; quick questions and free chat are there too.", fa: "دکمهٔ «درخشش» (✦) یا ⌘⇧D در نشانکِ انتخاب‌شده، پنل دستیار را باز می‌کند؛ پرسش‌های سریع و گفتگوی آزاد هم آنجاست.", ru: "Кнопка «Искра» (✦) или ⌘⇧D на выбранной закладке открывает панель ассистента; там же быстрые вопросы и свободный чат.", zh: "在所选书签上点「闪光」(✦) 按钮或按 ⌘⇧D 打开助手面板；快捷提问和自由对话也在那里。"),
        .init(en: "Page text is archived and feeds deep search and the AI assistant's context — even if the site goes offline.", fa: "متن صفحه آرشیو می‌شود و داخل جستجوی عمیق و زمینهٔ دستیار هوشمند می‌آید — حتی اگر سایت از دسترس خارج شود.", ru: "Текст страницы архивируется и попадает в глубокий поиск и контекст ИИ-ассистента — даже если сайт станет недоступен.", zh: "页面文本会被存档，供深度搜索和 AI 助手上下文使用 — 即使网站失效也可用。"),
        .init(en: "A background screenshot is captured and replaces the favicon in cards and boxes.", fa: "عکس پس‌زمینه گرفته می‌شود و جای فاوآیکون در کارت‌ها و باکس‌ها می‌نشیند.", ru: "Снимок страницы загружается и заменяет фавикон в карточках и боксах.", zh: "会截取背景截图，替换卡片和框中的网站图标。"),
        .init(en: "No duplicate bookmarks found", fa: "نشانک تکراری‌ای پیدا نشد", ru: "Дубликаты закладок не найдены", zh: "未发现重复书签"),
        .init(en: "Last check: %@", fa: "آخرین بررسی: %@", ru: "Последняя проверка: %@", zh: "上次检查：%@"),
        .init(en: "Bookmarks", fa: "نشانک‌ها", ru: "Закладки", zh: "书签"),
        .init(en: "%@ bookmarks will be deleted permanently.", fa: "%@ نشانک برای همیشه حذف خواهد شد.", ru: "%@ закладок будут удалены навсегда.", zh: "将永久删除 %@ 个书签。"),
        .init(en: "Remove duplicate bookmarks?", fa: "نشانک‌های تکراری حذف شوند؟", ru: "Удалить дубликаты закладок?", zh: "删除重复书签？"),
        .init(en: "Delete %@ Extra Copies", fa: "حذف %@ نسخهٔ اضافه", ru: "Удалить %@ лишних копий", zh: "删除 %@ 个多余副本"),
        .init(en: "%@ duplicate copies moved to Trash", fa: "%@ نسخهٔ تکراری به زباله‌دان رفت", ru: "%@ дубликатов перемещено в корзину", zh: "%@ 个重复副本已移入废纸篓"),
        .init(en: "In each group the newest copy is kept and the rest go to Trash.", fa: "در هر گروه، جدیدترین نسخه نگه داشته می‌شود و بقیه به زباله‌دان می‌روند.", ru: "В каждой группе остаётся самая новая копия, остальные уходят в корзину.", zh: "每组保留最新副本，其余移入废纸篓。"),
        .init(en: "Delete all dead bookmarks?", fa: "همهٔ نشانک‌های مرده حذف شوند؟", ru: "Удалить все мёртвые закладки?", zh: "删除所有失效书签？"),
        .init(en: "%@ bookmarks will be deleted.", fa: "%@ نشانک حذف خواهد شد.", ru: "Будет удалено закладок: %@.", zh: "将删除 %@ 个书签。"),
        .init(en: "✅ This model supports chat", fa: "✅ این مدل با گفتگو سازگار است", ru: "✅ Эта модель поддерживает чат", zh: "✅ 此模型支持对话"),
        .init(en: "❌ %@", fa: "❌ %@", ru: "❌ %@", zh: "❌ %@"),
        .init(en: "✅ Connected — “%@”", fa: "✅ اتصال برقرار — «%@»", ru: "✅ Соединение установлено — «%@»", zh: "✅ 连接成功 —「%@」"),
        .init(en: "Remove tag", fa: "حذف برچسب", ru: "Удалить тег", zh: "移除标签"),
        .init(en: "Choose a bookmark file exported from Safari, Chrome or Firefox", fa: "فایل بوکمارک خروجی‌گرفته‌شده از سافاری، کروم یا فایرفاکس را انتخاب کنید", ru: "Выберите файл закладок, экспортированный из Safari, Chrome или Firefox", zh: "请选择从 Safari、Chrome 或 Firefox 导出的书签文件"),
        .init(en: "Import", fa: "ورودی", ru: "Импорт", zh: "导入"),
        .init(en: "Save an HTML backup of all bookmarks", fa: "پشتیبان HTML از همهٔ نشانک‌ها ذخیره شود", ru: "Сохранить резервную копию HTML всех закладок", zh: "保存所有书签的 HTML 备份"),
        .init(en: "Appearance of Folder “%@”", fa: "ظاهر پوشهٔ «%@»", ru: "Внешний вид папки «%@»", zh: "文件夹「%@」的外观"),
        .init(en: "Color", fa: "رنگ", ru: "Цвет", zh: "颜色"),
        .init(en: "Icon", fa: "آیکون", ru: "Значок", zh: "图标"),
        .init(en: "Mind map is not saved. Close anyway?", fa: "نقشه ذخیره نشده است. ببندم؟", ru: "Карта не сохранена. Закрыть?", zh: "思维导图尚未保存，仍要关闭吗？"),
        .init(en: "Unsaved changes will be lost.", fa: "تغییرات ذخیره‌نشده از بین می‌روند.", ru: "Несохранённые изменения будут потеряны.", zh: "未保存的更改将丢失。"),
        .init(en: "Close Without Saving", fa: "بستن بدون ذخیره", ru: "Закрыть без сохранения", zh: "不保存并关闭"),
        .init(en: "Keep Editing", fa: "ادامه ویرایش", ru: "Продолжить редактирование", zh: "继续编辑"),
        .init(en: "Generate", fa: "تولید", ru: "Сгенерировать", zh: "生成"),
        .init(en: "Start", fa: "شروع", ru: "Запустить", zh: "开始"),
        .init(en: "Run the full pipeline", fa: "اجرای پایپ‌لاین کامل", ru: "Запустить полный конвейер", zh: "运行完整处理流程"),
        .init(en: "Stop", fa: "توقف", ru: "Остановить", zh: "停止"),
        .init(en: "Cancel network and AI requests", fa: "لغو شبکه و هوش مصنوعی", ru: "Отменить сетевые запросы и запросы к ИИ", zh: "取消网络与 AI 请求"),
        .init(en: "Regenerate", fa: "بازتولید", ru: "Сгенерировать заново", zh: "重新生成"),
        .init(en: "Ignore cache and build again", fa: "نادیده گرفتن کش و ساخت دوباره", ru: "Игнорировать кэш и построить заново", zh: "忽略缓存并重新构建"),
        .init(en: "Save this map as a separate record in the library", fa: "ذخیرهٔ این نقشه به‌عنوان رکورد مستقل در کتابخانه", ru: "Сохранить эту карту как отдельную запись в библиотеке", zh: "将此导图保存为书签库中的独立记录"),
        .init(en: "Save changes to this map", fa: "ذخیرهٔ تغییرات همین نقشه", ru: "Сохранить изменения этой карты", zh: "保存此导图的更改"),
        .init(en: "Open source page in browser", fa: "باز کردن صفحهٔ مبدأ در مرورگر", ru: "Открыть исходную страницу в браузере", zh: "在浏览器中打开来源页面"),
        .init(en: "Close Window (⌘W)", fa: "بستن پنجره (⌘W)", ru: "Закрыть окно (⌘W)", zh: "关闭窗口 (⌘W)"),
        .init(en: "Design a Mind Map from Page Content", fa: "طراحی نقشه ذهنی از محتوای یک صفحه", ru: "Построение интеллект-карты из содержимого страницы", zh: "根据网页内容设计思维导图"),
        .init(en: "Enter a page URL or use the selected bookmark. Five steps run: fetch page, extract content, convert to Markdown, analyze with AI, and build the map.", fa: "آدرس صفحه را وارد کنید یا نشانک انتخاب‌شده را انتخاب کنید. پنج مرحلهٔ دریافت صفحه، استخراج محتوا، تبدیل به مارک‌داون، تحلیل با هوش مصنوعی و ساخت نقشه اجرا می‌شود.", ru: "Введите адрес страницы или используйте выбранную закладку. Выполняются пять шагов: загрузка страницы, извлечение содержимого, преобразование в Markdown, анализ с помощью ИИ и построение карты.", zh: "输入网页地址或使用所选书签。将执行五个步骤：获取页面、提取内容、转换为 Markdown、AI 分析和构建导图。"),
        .init(en: "This bookmark has saved text that can be used if reading fails.", fa: "متن ذخیره‌شدهٔ این نشانک موجود است و در صورت شکست خواندن، قابل استفاده است.", ru: "У этой закладки есть сохранённый текст, который можно использовать при сбое чтения.", zh: "此书签已保存文本，读取失败时可以使用。"),
        .init(en: "Processing", fa: "در حال پردازش", ru: "Обработка", zh: "处理中"),
        .init(en: "Rendering map…", fa: "در حال رندر نقشه…", ru: "Отрисовка карты…", zh: "正在渲染导图…"),
        .init(en: "Zoom In (+)", fa: "بزرگ‌نمایی (+)", ru: "Увеличить (+)", zh: "放大 (+)"),
        .init(en: "Zoom Out (-)", fa: "کوچک‌نمایی (-)", ru: "Уменьшить (-)", zh: "缩小 (-)"),
        .init(en: "Fit to Window (0)", fa: "اندازه مناسب (۰)", ru: "По размеру окна (0)", zh: "适应窗口 (0)"),
        .init(en: "Add Child Node (Tab)", fa: "افزودن فرزند به گرهٔ انتخابی (Tab)", ru: "Добавить дочерний узел (Tab)", zh: "添加子节点 (Tab)"),
        .init(en: "Add Sibling Node (Enter)", fa: "افزودن خواهر/برادر (Enter)", ru: "Добавить узел того же уровня (Enter)", zh: "添加同级节点 (Enter)"),
        .init(en: "Delete Selected Node with Subtree (Delete)", fa: "حذف گرهٔ انتخابی با زیرشاخه‌ها (Delete)", ru: "Удалить выбранный узел с поддеревом (Delete)", zh: "删除所选节点及子树 (Delete)"),
        .init(en: "Expand All Branches", fa: "باز کردن همهٔ شاخه‌ها", ru: "Развернуть все ветви", zh: "展开所有分支"),
        .init(en: "Collapse All Branches", fa: "بستن همهٔ شاخه‌ها", ru: "Свернуть все ветви", zh: "折叠所有分支"),
        .init(en: "Layout: tree / org / radial / outline / both sides", fa: "چیدمان ساختاری: درختی / سازمانی / شعاعی / آوت‌لاین / دوطرفه", ru: "Макет: дерево / организация / радиальный / структура / двусторонний", zh: "布局：树状 / 组织 / 放射 / 大纲 / 双向"),
        .init(en: "Map Color Theme", fa: "تم رنگی نقشه", ru: "Цветовая тема карты", zh: "导图配色主题"),
        .init(en: "Layout direction: root left (default) or root right", fa: "جهت چیدمان: ریشه چپ (پیش‌فرض) یا ریشه راست", ru: "Направление: корень слева (по умолчанию) или справа", zh: "布局方向：根在左（默认）或根在右"),
        .init(en: "Search node text and highlight results", fa: "جستجو در متن گره‌ها و هایلایت نتایج", ru: "Поиск по тексту узлов и подсветка результатов", zh: "搜索节点文本并高亮结果"),
        .init(en: "Error", fa: "خطا", ru: "Ошибка", zh: "错误"),
        .init(en: "Technical Details", fa: "دلیل فنی", ru: "Технические подробности", zh: "技术详情"),
        .init(en: "Retry", fa: "تلاش مجدد", ru: "Повторить", zh: "重试"),
        .init(en: "Retry with Longer Timeout", fa: "تلاش با تأخیر بیشتر", ru: "Повторить с увеличенным таймаутом", zh: "以更长超时重试"),
        .init(en: "Paste Text Manually", fa: "چسباندن دستی متن", ru: "Вставить текст вручную", zh: "手动粘贴文本"),
        .init(en: "Paste the text here; it enters the pipeline at the AI analysis step.", fa: "متن را اینجا بچسبانید؛ از مرحلهٔ «تحلیل هوش مصنوعی» وارد پایپ‌لاین می‌شود.", ru: "Вставьте текст сюда; он поступит в конвейер с шага анализа ИИ.", zh: "在此粘贴文本；它将从 AI 分析步骤进入处理流程。"),
        .init(en: "Title (Optional)", fa: "عنوان (اختیاری)", ru: "Заголовок (необязательно)", zh: "标题（可选）"),
        .init(en: "Discard", fa: "انصراف", ru: "Отменить", zh: "放弃"),
        .init(en: "Running…", fa: "در حال اجرا…", ru: "Выполнение…", zh: "正在运行…"),
        .init(en: "Ready", fa: "آماده", ru: "Готово", zh: "就绪"),
        .init(en: "Drag nodes to rearrange; double-click a node to edit its text.", fa: "گره را بکشید و رها کنید؛ با دابل‌کلیک متن گره را ویرایش کنید.", ru: "Перетаскивайте узлы, чтобы изменить структуру; двойной клик редактирует текст узла.", zh: "拖动节点可调整位置；双击节点可编辑其文本。"),
        .init(en: "Render view is not ready.", fa: "صفحهٔ رندر آماده نیست.", ru: "Страница отрисовки не готова.", zh: "渲染页面尚未就绪。"),
        .init(en: "Failed to capture the map image.", fa: "عکس‌گرفتن از نقشه ناموفق بود.", ru: "Не удалось сделать снимок карты.", zh: "截取导图图像失败。"),
        .init(en: "Image conversion failed.", fa: "تبدیل عکس ناموفق بود.", ru: "Не удалось преобразовать изображение.", zh: "图像转换失败。"),
        .init(en: "%@ image saved", fa: "تصویر %@ ذخیره شد", ru: "Изображение %@ сохранено", zh: "%@ 图片已保存"),
        .init(en: "Failed to save image: %@", fa: "ذخیرهٔ تصویر ناموفق بود: %@", ru: "Не удалось сохранить изображение: %@", zh: "保存图片失败：%@"),
        .init(en: "Render files not found in the app bundle.", fa: "فایل‌های رندر در بستهٔ برنامه پیدا نشد.", ru: "Файлы отрисовки не найдены в пакете приложения.", zh: "在应用包中未找到渲染文件。"),
        .init(en: "Map data is not valid for HTML export.", fa: "دادهٔ نقشه برای خروجی HTML معتبر نیست.", ru: "Данные карты недопустимы для экспорта в HTML.", zh: "导图数据无法用于 HTML 导出。"),
        .init(en: "Standalone HTML page saved (works offline)", fa: "صفحهٔ HTML مستقل ذخیره شد (بدون نیاز به اینترنت)", ru: "Автономная HTML-страница сохранена (работает без интернета)", zh: "独立 HTML 页面已保存（离线可用）"),
        .init(en: "Failed to save HTML: %@", fa: "ذخیرهٔ HTML ناموفق بود: %@", ru: "Не удалось сохранить HTML: %@", zh: "保存 HTML 失败：%@"),
        .init(en: "Full save will be enabled in phase 4 (database)", fa: "ذخیرهٔ کامل در فاز ۴ (پایگاه‌داده) فعال می‌شود", ru: "Полное сохранение будет включено на этапе 4 (база данных)", zh: "完整保存将在第 4 阶段（数据库）启用"),
        .init(en: "Mind Map Tab", fa: "نقشه ذهنی", ru: "Интеллект-карта", zh: "思维导图"),
        .init(en: "Tree View", fa: "نمای درختی", ru: "В виде дерева", zh: "树状视图"),
        .init(en: "Source Markdown", fa: "مارک‌داون منبع", ru: "Исходный Markdown", zh: "源 Markdown"),
        .init(en: "JSON Structure", fa: "ساختار JSON", ru: "Структура JSON", zh: "JSON 结构"),
        .init(en: "Fetch Page", fa: "دریافت صفحه", ru: "Загрузка страницы", zh: "获取页面"),
        .init(en: "Extract Main Content", fa: "استخراج محتوای اصلی", ru: "Извлечение основного содержимого", zh: "提取主要内容"),
        .init(en: "Convert to Markdown", fa: "تبدیل به مارک‌داون", ru: "Преобразование в Markdown", zh: "转换为 Markdown"),
        .init(en: "AI Analysis", fa: "تحلیل هوش مصنوعی", ru: "Анализ с помощью ИИ", zh: "AI 分析"),
        .init(en: "Build Map", fa: "ساخت نقشه", ru: "Построение карты", zh: "构建导图"),
        .init(en: "Saved map opened from library · %@ nodes", fa: "نقشهٔ ذخیره‌شده از کتابخانه باز شد · %@ گره", ru: "Сохранённая карта открыта из библиотеки · %@ узлов", zh: "已从书签库打开保存的导图 · %@ 个节点"),
        .init(en: "Invalid URL.", fa: "لینک معتبر نیست.", ru: "Недопустимая ссылка.", zh: "网址无效。"),
        .init(en: "Only http and https URLs are accepted.", fa: "فقط آدرس‌های http و https پذیرفته می‌شوند.", ru: "Принимаются только адреса http و https.", zh: "仅接受 http 和 https 网址。"),
        .init(en: "Starting the page pipeline", fa: "شروع پایپ‌لاین واقعی صفحه", ru: "Запуск конвейера обработки страницы", zh: "正在启动页面处理流程"),
        .init(en: "Loading page in a sandboxed WebKit…", fa: "بارگذاری صفحه با WebKit ایزوله…", ru: "Загрузка страницы в изолированном WebKit…", zh: "正在通过沙盒 WebKit 加载页面…"),
        .init(en: "Page loaded; Readability is extracting the main content…", fa: "صفحه بارگذاری شد؛ Readability در حال استخراج محتوای اصلی است…", ru: "Страница загружена; Readability извлекает основное содержимое…", zh: "页面已加载；Readability 正在提取主要内容…"),
        .init(en: "Not enough content could be extracted from this page.", fa: "محتوای کافی از این صفحه استخراج نشد.", ru: "Со страницы не удалось извлечь достаточно содержимого.", zh: "未能从此页面提取到足够内容。"),
        .init(en: "%@ words extracted from %@; analyzing with AI…", fa: "%@ واژه از %@ استخراج شد؛ در حال تحلیل هوش مصنوعی…", ru: "Извлечено %@ слов из %@; идёт анализ с помощью ИИ…", zh: "从%@提取了 %@ 个词；正在进行 AI 分析…"),
        .init(en: "Map built and saved separately in Mind Maps · %@ nodes", fa: "نقشه ساخته و جداگانه در «نقشه‌های ذهنی» ذخیره شد · %@ گره", ru: "Карта построена и сохранена отдельно в «Интеллект-картах» · %@ узлов", zh: "导图已构建并单独保存到「思维导图」 · %@ 个节点"),
        .init(en: "Map built · %@ nodes; saving to library failed.", fa: "نقشه ساخته شد · %@ گره؛ ذخیره در کتابخانه ناموفق بود.", ru: "Карта построена · %@ узлов; не удалось сохранить в библиотеку.", zh: "导图已构建 · %@ 个节点；保存到书签库失败。"),
        .init(en: "Failed to build the map.", fa: "ساخت نقشه انجام نشد.", ru: "Не удалось построить карту.", zh: "构建导图失败。"),
        .init(en: "Stopped", fa: "متوقف شد", ru: "Остановлено", zh: "已停止"),
        .init(en: "Not enough content.", fa: "محتوای کافی نیست.", ru: "Недостаточно содержимого.", zh: "内容不足。"),
        .init(en: "Pasted Text", fa: "متن چسبانده‌شده", ru: "Вставленный текст", zh: "粘贴的文本"),
        .init(en: "Building map from pasted text…", fa: "در حال ساخت نقشه از متن دستی…", ru: "Построение карты из вставленного текста…", zh: "正在根据粘贴文本构建导图…"),
        .init(en: "Manual Text", fa: "متن دستی", ru: "Ручной текст", zh: "手动文本"),
        .init(en: "Map built from pasted text and saved to library · %@ nodes", fa: "نقشه از متن دستی ساخته و در کتابخانه ذخیره شد · %@ گره", ru: "Карта построена из вставленного текста и сохранена в библиотеку · %@ узлов", zh: "已根据粘贴文本构建导图并保存到书签库 · %@ 个节点"),
        .init(en: "Map built from pasted text; saving to library failed.", fa: "نقشه از متن دستی ساخته شد؛ ذخیره در کتابخانه ناموفق بود.", ru: "Карта построена из вставленного текста; не удалось сохранить в библиотеку.", zh: "已根据粘贴文本构建导图；保存到书签库失败。"),
        .init(en: "Failed to analyze pasted text.", fa: "تحلیل متن دستی انجام نشد.", ru: "Не удалось проанализировать вставленный текст.", zh: "分析粘贴文本失败。"),
        .init(en: "Map changes not saved", fa: "تغییر نقشه ذخیره نشده است", ru: "Изменения карты не сохранены", zh: "导图更改未保存"),
        .init(en: "Map saved as a separate record", fa: "نقشه به‌صورت رکورد مستقل ذخیره شد", ru: "Карта сохранена как отдельная запись", zh: "导图已保存为独立记录"),
        .init(en: "Failed to save the map.", fa: "ذخیرهٔ نقشه ناموفق بود.", ru: "Не удалось сохранить карту.", zh: "保存导图失败。"),
        .init(en: "Assistant for This Bookmark", fa: "دستیار دربارهٔ این نشانک", ru: "Ассистент для этой закладки", zh: "此书签的助手"),
        .init(en: "Latest recorded decision", fa: "آخرین تصمیم ثبت‌شده", ru: "Последнее записанное решение", zh: "最近记录的决定"),
        .init(en: "Page text not read yet", fa: "متن صفحه خوانده نشده", ru: "Текст страницы ещё не прочитан", zh: "尚未读取页面文本"),
        .init(en: "The assistant reads the page on your first question.", fa: "دستیار هنگام نخستین پرسش، خودش صفحه را می‌خواند.", ru: "Ассистент сам прочитает страницу при первом вопросе.", zh: "助手会在您首次提问时自动读取页面。"),
        .init(en: "All Chats", fa: "همهٔ گفتگوها", ru: "Все чаты", zh: "所有聊天"),
        .init(en: "Start Over (Clear Messages)", fa: "شروع از نو (پاک‌کردن پیام‌ها)", ru: "Начать заново (очистить сообщения)", zh: "重新开始（清空消息）"),
        .init(en: "Delete This Chat", fa: "حذف این گفتگو", ru: "Удалить этот чат", zh: "删除此聊天"),
        .init(en: "Log Decision…", fa: "ثبت تصمیم…", ru: "Записать решение…", zh: "记录决定…"),
        .init(en: "Chat Actions", fa: "کارهای گفتگو", ru: "Действия с чатом", zh: "聊天操作"),
        .init(en: "Record your decision", fa: "تصمیم خودت را ثبت کن", ru: "Запишите своё решение", zh: "记录您的决定"),
        .init(en: "Note (optional)", fa: "یادداشت (اختیاری)", ru: "Заметка (необязательно)", zh: "备注（可选）"),
        .init(en: "Logged to decision log", fa: "در لاگ تصمیم ثبت شد", ru: "Записано в журнал решений", zh: "已记录到决定日志"),
        .init(en: "Reading page…", fa: "در حال خواندن صفحه…", ru: "Чтение страницы…", zh: "正在读取页面…"),
        .init(en: "Thinking…", fa: "در حال فکر کردن…", ru: "Думаю…", zh: "思考中…"),
        .init(en: "Ask the assistant your question", fa: "سؤالتان را از دستیار بپرسید", ru: "Задайте вопрос ассистенту", zh: "向助手提问"),
        .init(en: "The assistant checks this page against your profile and tells you whether it is useful for you.", fa: "دستیار این صفحه را با پروفایل شما می‌سنجد و می‌گوید به دردتان می‌خورد یا نه.", ru: "Ассистент оценивает эту страницу с учётом вашего профиля и говорит, полезна ли она вам.", zh: "助手会结合您的个人画像评估此页面，并告诉您它是否对您有用。"),
        .init(en: "For more targeted answers, write your profile in Settings first.", fa: "برای پاسخ‌های هدفمندتر، اول پروفایل خود را در تنظیمات بنویسید.", ru: "Для более точных ответов сначала заполните свой профиль в настройках.", zh: "如需更有针对性的回答，请先在设置中填写您的画像。"),
        .init(en: "Decision:", fa: "تصمیم:", ru: "Решение:", zh: "决定："),
        .init(en: "Logged “%@”", fa: "«%@» ثبت شد", ru: "Записано «%@»", zh: "已记录「%@」"),
        .init(en: "Last: %@", fa: "آخرین: %@", ru: "Последнее: %@", zh: "最近：%@"),
        .init(en: "e.g. Is this monitor good for color design?", fa: "مثلاً: آیا این مانیتور برای طراحی رنگ مناسب است؟", ru: "Например: подойдёт ли этот монитор для работы с цветом?", zh: "例如：这款显示器适合做色彩设计吗？"),
        .init(en: "This chat is saved; continue it later from Chats (⌘⇧C).", fa: "این گفتگو ذخیره می‌شود؛ از «گفتگوها» (⌘⇧C) بعداً ادامه‌اش بده.", ru: "Этот чат сохраняется; продолжите его позже в разделе «Чаты» (⌘⇧C).", zh: "此聊天会保存；稍后可从「聊天」(⌘⇧C) 继续。"),
        .init(en: "Command, bookmark or question…", fa: "دستور، نشانک یا پرسش…", ru: "Команда, закладка или вопрос…", zh: "命令、书签或问题…"),
        .init(en: "Nothing found", fa: "چیزی پیدا نشد", ru: "Ничего не найдено", zh: "未找到任何内容"),
        .init(en: "Navigate", fa: "جابه‌جایی", ru: "Перемещение", zh: "移动"),
        .init(en: "Run", fa: "اجرا", ru: "Запустить", zh: "执行"),
        .init(en: "%@ bookmarks in this scope", fa: "%@ نشانک در این محدوده", ru: "Закладок в этой области: %@", zh: "此范围内有 %@ 个书签"),
        .init(en: "Ask", fa: "پرسش", ru: "Спросить", zh: "询问"),
        .init(en: "Chat · %@ messages", fa: "گفتگو · %@ پیام", ru: "Чат · %@ сообщений", zh: "聊天 · %@ 条消息"),
        .init(en: "Ask the library: “%@”", fa: "از کل کتابخانه بپرس: «%@»", ru: "Спросить библиотеку: «%@»", zh: "询问书签库：「%@」"),
        .init(en: "Answer with references to your bookmarks", fa: "پاسخ با ارجاع به نشانک‌های خودت", ru: "Ответ со ссылками на ваши закладки", zh: "回答将引用您的书签"),
        .init(en: "Ask about the selected bookmark: “%@”", fa: "پرسش دربارهٔ نشانک انتخاب‌شده: «%@»", ru: "Спросить о выбранной закладке: «%@»", zh: "询问所选书签：「%@」"),
        .init(en: "No bookmark selected", fa: "نشانکی انتخاب نشده", ru: "Закладка не выбрана", zh: "未选择书签"),
        .init(en: "Chat about “%@”", fa: "گفتگو دربارهٔ «%@»", ru: "Чат о «%@»", zh: "关于「%@」的聊天"),
        .init(en: "Tag · %@", fa: "برچسب · %@", ru: "Тег · %@", zh: "标签 · %@"),
        .init(en: "Settings", fa: "تنظیمات", ru: "Настройки", zh: "设置"),
        .init(en: "Assistant, appearance, data", fa: "دستیار، ظاهر، داده‌ها", ru: "Ассистент, оформление, данные", zh: "助手、外观、数据"),
        .init(en: "Neshank", fa: "نشانک", ru: "Neshank", zh: "书签"),
        .init(en: "Open Main Window", fa: "باز کردن پنجرهٔ اصلی", ru: "Открыть главное окно", zh: "打开主窗口"),
        .init(en: "Search or type a URL…", fa: "جستجو یا نوشتن آدرس…", ru: "Поиск или ввод адреса…", zh: "搜索或输入网址…"),
        .init(en: "You have no bookmarks yet", fa: "هنوز نشانکی ندارید", ru: "У вас пока нет закладок", zh: "还没有任何书签"),
        .init(en: "Quit", fa: "خروج", ru: "Завершить", zh: "退出"),
        .init(en: "%@ bookmarks", fa: "%@ نشانک", ru: "Закладок: %@", zh: "%@ 个书签"),
        .init(en: "No URL in the clipboard", fa: "آدرسی در کلیپ‌بورد نیست", ru: "В буфере обмена нет адреса", zh: "剪贴板中没有网址"),
        .init(en: "Adding…", fa: "در حال افزودن…", ru: "Добавление…", zh: "正在添加…"),
        .init(en: "Bookmark added", fa: "نشانک افزوده شد", ru: "Закладка добавлена", zh: "书签已添加"),
        .init(en: "From anywhere, ⌘⇧Space", fa: "هر کجا هستید ⌘⇧Space", ru: "Из любого приложения, ⌘⇧Space", zh: "随时随地，⌘⇧Space"),
        .init(en: "Paste a URL…", fa: "آدرس را بچسبانید…", ru: "Вставьте адрес…", zh: "粘贴网址…"),
        .init(en: "Auto-fetch info", fa: "دریافت خودکار اطلاعات", ru: "Автополучение данных", zh: "自动获取信息"),
        .init(en: "Fetching page info…", fa: "در حال دریافت اطلاعات صفحه…", ru: "Получение данных страницы…", zh: "正在获取页面信息…"),
        .init(en: "Add Bookmark", fa: "افزودن نشانک", ru: "Добавить закладку", zh: "添加书签"),
        .init(en: "Bookmark saved ✓", fa: "نشانک ذخیره شد ✓", ru: "Закладка сохранена ✓", zh: "书签已保存 ✓"),
        .init(en: "Title (empty = auto-fetch)", fa: "عنوان (خالی = دریافت خودکار)", ru: "Заголовок (пусто = автополучение)", zh: "标题（留空 = 自动获取）"),
        .init(en: "Tags (comma-separated)", fa: "برچسب‌ها (جداشده با ویرگول)", ru: "Теги (через запятую)", zh: "标签（以逗号分隔）"),
        .init(en: "Auto-fetch title, description and image", fa: "دریافت خودکار عنوان، توضیح و تصویر", ru: "Автополучение заголовка, описания و изображения", zh: "自动获取标题、描述和图片"),
        .init(en: "Invalid URL", fa: "آدرس نامعتبر است", ru: "Неверный адрес", zh: "网址无效"),
        .init(en: "Save Changes", fa: "ذخیرهٔ تغییرات", ru: "Сохранить изменения", zh: "保存更改"),
        .init(en: "Newest", fa: "جدیدترین", ru: "Сначала новые", zh: "最新"),
        .init(en: "Oldest", fa: "قدیمی‌ترین", ru: "Сначала старые", zh: "最早"),
        .init(en: "Website", fa: "وب‌سایت", ru: "Сайт", zh: "网站"),
        .init(en: "List", fa: "فهرست", ru: "Список", zh: "列表"),
        .init(en: "Cards", fa: "کارت‌ها", ru: "Карточки", zh: "卡片"),
        .init(en: "Grid", fa: "سه‌ستونی", ru: "Сетка", zh: "网格"),
        .init(en: "Failed to load: %@", fa: "خطا در بارگذاری: %@", ru: "Ошибка загрузки: %@", zh: "加载失败：%@"),
        .init(en: "Failed to save mind map: %@", fa: "ذخیرهٔ نقشه ناموفق بود: %@", ru: "Не удалось сохранить интеллект-карту: %@", zh: "保存思维导图失败：%@"),
        .init(en: "Failed to save mind map changes: %@", fa: "ذخیرهٔ تغییرات نقشه ناموفق بود: %@", ru: "Не удалось сохранить изменения карты: %@", zh: "保存思维导图修改失败：%@"),
        .init(en: "%@ mind maps deleted from the library; original bookmarks untouched", fa: "%@ نقشه از کتابخانه حذف شد؛ نشانک‌های اصلی دست‌نخورده‌اند", ru: "Из библиотеки удалены карты: %@; исходные закладки не тронуты", zh: "已从书签库删除 %@ 张思维导图；原书签保持不变"),
        .init(en: "Failed to delete mind map: %@", fa: "حذف نقشه ناموفق بود: %@", ru: "Не удалось удалить интеллект-карту: %@", zh: "删除思维导图失败：%@"),
        .init(en: "Failed to save: %@", fa: "خطا در ذخیره: %@", ru: "Ошибка сохранения: %@", zh: "保存失败：%@"),
        .init(en: "Bookmark saved", fa: "نشانک ذخیره شد", ru: "Закладка сохранена", zh: "书签已保存"),
        .init(en: "Failed to edit: %@", fa: "خطا در ویرایش: %@", ru: "Ошибка изменения: %@", zh: "编辑失败：%@"),
        .init(en: "%@ bookmarks moved to Trash (⌘Z to undo)", fa: "%@ نشانک به زباله‌دان رفت (⌘Z برای بازگردانی)", ru: "Закладки перемещены в корзину: %@ (⌘Z — вернуть)", zh: "已将 %@ 个书签移到废纸篓（⌘Z 撤销）"),
        .init(en: "Failed to delete: %@", fa: "خطا در حذف: %@", ru: "Ошибка удаления: %@", zh: "删除失败：%@"),
        .init(en: "%@ bookmarks restored", fa: "%@ نشانک بازگردانی شد", ru: "Закладки восстановлены: %@", zh: "已恢复 %@ 个书签"),
        .init(en: "Trash is empty", fa: "زباله‌دان خالی است", ru: "Корзина пуста", zh: "废纸篓是空的"),
        .init(en: "%@ bookmarks deleted permanently", fa: "%@ نشانک برای همیشه حذف شد", ru: "Закладки удалены навсегда: %@", zh: "已永久删除 %@ 个书签"),
        .init(en: "Tag “%@” added", fa: "برچسب «%@» افزوده شد", ru: "Тег «%@» добавлен", zh: "已添加标签“%@”"),
        .init(en: "Failed to create folder: %@", fa: "پوشه ساخته نشد: %@", ru: "Не удалось создать папку: %@", zh: "创建文件夹失败：%@"),
        .init(en: "Folder deleted; subfolders moved up one level", fa: "پوشه حذف شد؛ زیرپوشه‌ها یک سطح بالا آمدند", ru: "Папка удалена; вложенные папки подняты на уровень выше", zh: "文件夹已删除；子文件夹上移一级"),
        .init(en: "Give the filter a name", fa: "برای فیلتر نامی بگذارید", ru: "Задайте имя фильтра", zh: "请为筛选器命名"),
        .init(en: "Filter saved", fa: "فیلتر ذخیره شد", ru: "Фильтر сохранён", zh: "筛选器已保存"),
        .init(en: "Failed to save filter: %@", fa: "فیلتر ذخیره نشد: %@", ru: "Не удалось сохранить фильтر: %@", zh: "保存筛选器失败：%@"),
        .init(en: "Filter “%@” applied", fa: "فیلتر «%@» اعمال شد", ru: "Фильтر «%@» применён", zh: "已应用筛选器“%@”"),
        .init(en: "Filter deleted", fa: "فیلتر حذف شد", ru: "Фильтر удалён", zh: "筛选器已删除"),
        .init(en: "URL copied", fa: "آدرس کپی شد", ru: "Адрес скопирован", zh: "网址已复制"),
        .init(en: "Could not read file", fa: "فایل خوانده نشد", ru: "Не удалось прочитать файл", zh: "无法读取文件"),
        .init(en: "No bookmarks found in file", fa: "نشانکی در فایل پیدا نشد", ru: "В файле не найдено закладок", zh: "文件中未找到书签"),
        .init(en: "%@ bookmarks imported", fa: "%@ نشانک وارد شد", ru: "Закладки импортированы: %@", zh: "已导入 %@ 个书签"),
        .init(en: "HTML backup saved", fa: "پشتیبان HTML ذخیره شد", ru: "HTML-резервная копия сохранена", zh: "HTML 备份已保存"),
        .init(en: "Export failed: %@", fa: "خطا در خروجی: %@", ru: "Ошибка экспорта: %@", zh: "导出失败：%@"),
        .init(en: "No bookmarks to check", fa: "نشانکی برای بررسی نیست", ru: "Нет закладок для проверки", zh: "没有要检查的书签"),
        .init(en: "Link check finished", fa: "بررسی لینک‌ها تمام شد", ru: "Проверка ссылок завершена", zh: "链接检查完成"),
        .init(en: "System", fa: "هماهنگ با سیستم", ru: "Системная", zh: "跟随系统"),
        .init(en: "Light", fa: "روشن", ru: "Светлая", zh: "浅色"),
        .init(en: "Dark", fa: "تاریک", ru: "Тёмная", zh: "深色"),
        .init(en: "Compact", fa: "فرود (فشرده)", ru: "Компактная", zh: "紧凑"),
        .init(en: "Comfortable", fa: "راحت", ru: "Просторная", zh: "舒适"),
        .init(en: "No Grouping", fa: "بدون گروه‌بندی", ru: "Без группировки", zh: "不分组"),
        .init(en: "By Domain", fa: "بر اساس دامنه", ru: "По домену", zh: "按域名"),
        .init(en: "By Month", fa: "بر اساس ماه", ru: "По месяцу", zh: "按月份"),
        .init(en: "By Folder", fa: "بر اساس پوشه", ru: "По папке", zh: "按文件夹"),
        .init(en: "Blue", fa: "آبی", ru: "Синий", zh: "蓝色"),
        .init(en: "Teal", fa: "فیروزه‌ای", ru: "Бирюзовый", zh: "青色"),
        .init(en: "Green", fa: "سبز", ru: "Зелёный", zh: "绿色"),
        .init(en: "Indigo", fa: "نیلی", ru: "Индиго", zh: "靛蓝色"),
        .init(en: "Purple", fa: "بنفش", ru: "Фиолетовый", zh: "紫色"),
        .init(en: "Pink", fa: "صورتی", ru: "Розовый", zh: "粉色"),
        .init(en: "Orange", fa: "نارنجی", ru: "Оранжевый", zh: "橙色"),
        .init(en: "Red", fa: "قرمز", ru: "Красный", zh: "红色"),
        .init(en: "Graphite", fa: "گرافیتی", ru: "Графитовый", zh: "石墨色"),
        .init(en: "Olive", fa: "زیتونی", ru: "Оливковый", zh: "橄榄色"),
        .init(en: "Brown", fa: "قهوه‌ای", ru: "Коричневый", zh: "棕色"),
        .init(en: "Sky", fa: "آسمانی", ru: "Небесно-голубой", zh: "天蓝色"),
        .init(en: "Off", fa: "غیرفعال", ru: "Выключено", zh: "关闭"),
        .init(en: "Yellow", fa: "زرد", ru: "Жёлтый", zh: "黄色"),
        .init(en: "Library", fa: "کتابخانه", ru: "Библиотека", zh: "书签库"),
        .init(en: "Me", fa: "من", ru: "Я", zh: "我"),
        .init(en: "Buy", fa: "خریدم", ru: "Купить", zh: "购买"),
        .init(en: "Don't Buy", fa: "نخریدم", ru: "Не покупать", zh: "不购买"),
        .init(en: "Not Now", fa: "فعلاً نه", ru: "Пока не надо", zh: "暂不"),
        .init(en: "Quick Add…", fa: "افزودن سریع…", ru: "Быстрое добавление…", zh: "快速添加…"),
        .init(en: "Command Palette…", fa: "پالت فرمان…", ru: "Палитра команд…", zh: "命令面板…"),
        .init(en: "Chats…", fa: "گفتگوها…", ru: "Чаты…", zh: "聊天…"),
        .init(en: "Forest", fa: "جنگل", ru: "Лес", zh: "森林"),
        .init(en: "Ocean", fa: "اقیانوس", ru: "Океан", zh: "海洋"),
        .init(en: "Sunset", fa: "غروب", ru: "Закат", zh: "日落"),
        .init(en: "Lavender", fa: "بنفشه", ru: "Лаванда", zh: "薰衣草"),
        .init(en: "Monochrome", fa: "تک‌رنگ", ru: "Монохром", zh: "单色"),
        .init(en: "Sand", fa: "کویر", ru: "Пустыня", zh: "沙漠"),
        .init(en: "Sakura", fa: "شکوفه", ru: "Сакура", zh: "樱花"),
        .init(en: "Mint", fa: "نعنا", ru: "Мята", zh: "薄荷"),
        .init(en: "Horizontal Tree", fa: "درختی افقی", ru: "Горизонтальное дерево", zh: "水平树状"),
        .init(en: "Organizational (Vertical)", fa: "سازمانی (عمودی)", ru: "Организационная (вертикальная)", zh: "组织结构（垂直）"),
        .init(en: "Radial", fa: "شعاعی", ru: "Радиальная", zh: "放射状"),
        .init(en: "Outline", fa: "آوت‌لاین", ru: "Структура", zh: "大纲"),
        .init(en: "Two-Sided (Timeline)", fa: "دوطرفه (تایم‌لاین)", ru: "Двустороннее (таймлайн)", zh: "双向（时间线）"),
        .init(en: "Root Left (Default)", fa: "ریشه چپ (پیش‌فرض)", ru: "Корень слева (по умолчанию)", zh: "根在左侧（默认）"),
        .init(en: "Root Right", fa: "ریشه راست", ru: "Корень справا", zh: "根在右侧"),
        .init(en: "The render page has not been created yet.", fa: "صفحهٔ رندر هنوز ساخته نشده است.", ru: "Страница отрисовки ещё не создана.", zh: "渲染页面尚未创建。"),
        .init(en: "The render page has not loaded yet.", fa: "صفحهٔ رندر هنوز بارگذاری نشده است.", ru: "Страница отрисовки ещё не загружена.", zh: "渲染页面尚未加载。"),
        .init(en: "Render script failed to run", fa: "اسکریپت رندر اجرا نشد", ru: "Не удалось выполнить скрипт отрисовки", zh: "渲染脚本未能运行"),
        .init(en: "Rendering failed.", fa: "رندر ناموفق بود.", ru: "Не удалось выполнить отрисовку.", zh: "渲染失败。"),
        .init(en: "The mind map render file was not found in the app bundle.", fa: "فایل رندر نقشه در بستهٔ برنامه پیدا نشد.", ru: "Файл отрисовки интеллект-карты не найден в ресурсах приложения.", zh: "未在应用资源中找到思维导图渲染文件。"),
        .init(en: "My Bookmarks", fa: "نشانک‌های من", ru: "Мои закладки", zh: "我的书签"),
        .init(en: "Enough text was found to build the mind map.", fa: "متن کافی برای ساخت نقشه پیدا شد.", ru: "Найдено достаточно текста для построения интеллект-карты.", zh: "已找到足够文本，可构建思维导图。"),
        .init(en: "Only the page title was extracted; a mind map is not built from the title alone.", fa: "فقط عنوان صفحه استخراج شد؛ از عنوان تنها نقشه ساخته نمی‌شود.", ru: "Извлечён только заголовок страницы; карта по одному заголовку не строится.", zh: "仅提取到页面标题；不会仅凭标题构建思维导图。"),
        .init(en: "The extracted text looks like a menu/site shell, not main content.", fa: "متن استخراج‌شده شبیه منو/پوستهٔ سایت است، نه محتوای اصلی.", ru: "Похоже, извлечена оболочка меню/сайта, а не основной контент.", zh: "提取的文本像是菜单/网站外壳，而非正文内容。"),
        .init(en: "Not enough content was extracted from this page; paste the text manually or try a longer delay.", fa: "محتوای کافی از این صفحه استخراج نشد؛ متن را دستی بچسبانید یا تأخیر بیشتر را امتحان کنید.", ru: "С этой страницы не удалось извлечь достаточно контента; вставьте текст вручную или попробуйте большую задержку.", zh: "未能从此页面提取足够内容；请手动粘贴文本或尝试更长的延迟。"),
        .init(en: "The link is not valid; only http and https addresses are accepted.", fa: "لینک معتبر نیست؛ فقط آدرس‌های http و https پذیرفته می‌شود.", ru: "Недопустимая ссылка; принимаются только адреса http و https.", zh: "链接无效；仅接受 http 和 https 地址。"),
        .init(en: "Failed to load page extractor local files: %@", fa: "فایل‌های محلی استخراج صفحه بارگذاری نشدند: %@", ru: "Не удалось загрузить локальные файлы извлечения страницы: %@", zh: "未能加载页面提取器的本地文件：%@"),
        .init(en: "The browser could not load the page.", fa: "مرورگر نتوانست صفحه را بارگذاری کند.", ru: "Браузеру не удалось загрузить страницу.", zh: "浏览器无法加载该页面。"),
        .init(en: "Page load error: %@", fa: "خطای بارگذاری صفحه: %@", ru: "Ошибка загрузки страницы: %@", zh: "页面加载错误：%@"),
        .init(en: "The page returned HTTP status %@.", fa: "صفحه پاسخ HTTP %@ برگرداند.", ru: "Страница вернула HTTP-статус %@.", zh: "页面返回了 HTTP 状态码 %@。"),
        .init(en: "Loading the page took too long; try the “Retry with longer delay” option.", fa: "بارگذاری صفحه بیش از حد طول کشید؛ گزینهٔ «تلاش با تأخیر بیشتر» را امتحان کنید.", ru: "Загрузка страницы заняла слишком много времени; попробуйте вариант «Повторить с большей задержкой».", zh: "页面加载耗时过长；请尝试“以更长延迟重试”选项。"),
        .init(en: "Not enough content was extracted from this page; you can paste the text manually. Technical details: title=%@, region=%@, markdown=%d, html=%d, headings=%d, readability=%@.", fa: "محتوای کافی از این صفحه استخراج نشد؛ می‌توانید متن را دستی بچسبانید. تشخیص فنی: title=%@, region=%@, markdown=%d, html=%d, headings=%d, readability=%@.", ru: "Не удалось извлечь достаточно контента с этой страницы; текст можно вставить вручную. Технические сведения: title=%@, region=%@, markdown=%d, html=%d, headings=%d, readability=%@.", zh: "未能从此页面提取足够内容；可手动粘贴文本。技术信息：title=%@, region=%@, markdown=%d, html=%d, headings=%d, readability=%@。"),
        .init(en: "The extractor did not return a structured response (response type: %@).", fa: "استخراج‌گر پاسخ ساختاریافته برنگرداند (نوع پاسخ: %@)", ru: "Извлекатель не вернул структурированный ответ (тип ответа: %@).", zh: "提取器未返回结构化响应（响应类型：%@）。"),
        .init(en: "The extractor did not return a final URL.", fa: "استخراج‌گر URL نهایی برنگرداند.", ru: "Извлекатель не вернул итоговый URL.", zh: "提取器未返回最终网址。"),
        .init(en: "Readability.js or Turndown.js file is empty", fa: "فایل Readability.js یا Turndown.js خالی است", ru: "Файл Readability.js или Turndown.js пуст", zh: "Readability.js 或 Turndown.js 文件为空"),
        .init(en: "Readability.js or Turndown.js was not found", fa: "Readability.js یا Turndown.js پیدا نشد", ru: "Readability.js یا Turndown.js не найдены", zh: "未找到 Readability.js 或 Turndown.js"),
        .init(en: "This test build does not include SwiftPM resources", fa: "این بیلد تستی منابع SwiftPM را ندارد", ru: "Эта тестовая сборка не содержит ресурсов SwiftPM", zh: "此测试版本不包含 SwiftPM 资源"),
        .init(en: "Error opening database: %@", fa: "خطا در باز کردن پایگاه داده: %@", ru: "Ошибка при открытии базы данных: %@", zh: "打开数据库时出错：%@"),
        .init(en: "SQL command error: %@", fa: "خطای فرمان SQL: %@", ru: "Ошибка команды SQL: %@", zh: "SQL 命令错误：%@"),
        .init(en: "SQL execution error: %@", fa: "خطای اجرای فرمان SQL: %@", ru: "Ошибка выполнения команды SQL: %@", zh: "SQL 执行错误：%@"),
        .init(en: "Assistant key is not set (Settings → AI Assistant).", fa: "کلید دستیار تنظیم نشده است (تنظیمات ← دستیار هوشمند).", ru: "Ключ ассистента не задан (Настройки → ИИ-ассистент).", zh: "未设置助手密钥（设置 → AI 助手）。"),
        .init(en: "The assistant service address is invalid.", fa: "آدرس سرویس دستیار نامعتبر است.", ru: "Адрес сервиса ассистента недействителен.", zh: "助手服务地址无效。"),
        .init(en: "Network error: %@", fa: "خطای شبکه: %@", ru: "Ошибка сети: %@", zh: "网络错误：%@"),
        .init(en: "Service response (%@): %@", fa: "پاسخ سرویس (%@): %@", ru: "Ответ сервиса (%@): %@", zh: "服务响应 (%@)：%@"),
        .init(en: "The response was empty; please try again.", fa: "پاسخ خالی برگشت؛ یک بار دیگر امتحان کنید.", ru: "Ответ был пустым; попробуйте ещё раз.", zh: "响应为空；请重试。"),
        .init(en: "The model could not finish within the token limit (its internal reasoning got too long); try again or shorten the page text.", fa: "مدل با سقف توکن نتوانست پاسخ کامل بدهد (استدلال داخلی‌اش بیش از حد طولانی شد)؛ دوباره تلاش کن یا متن صفحه را کوتاه‌تر کن.", ru: "Модель не уложилась в лимит токенов (её внутренние рассуждения стали слишком длинными); попробуйте снова или сократите текст страницы.", zh: "模型未能在令牌限额内完成（内部推理过长）；请重试或缩短页面文本。"),
        .init(en: "The model list could not be read: %@", fa: "فهرست مدل‌ها قابل خواندن نبود: %@", ru: "Не удалось прочитать список моделей: %@", zh: "无法读取模型列表：%@"),
        .init(en: "The service returned no models; enter the model name manually.", fa: "سرویس هیچ مدلی برنگرداند؛ نام مدل را دستی وارد کنید.", ru: "Сервис не вернул ни одной модели; введите название модели вручную.", zh: "服务未返回任何模型；请手动输入模型名称。"),
        .init(en: "This model is not compatible with the service chat protocol — in Settings → AI Assistant, pick another model from the list (e.g. deepseek-v4.1-flash). Service message: %@", fa: "این مدل با پروتکل گفتگوی سرویس سازگار نیست — در تنظیمات ← دستیار هوشمند، مدل دیگری از فهرست انتخاب کنید (مثلاً deepseek-v4.1-flash). پیام سرویس: %@", ru: "Эта модель несовместима с протоколом чата сервиса — в «Настройки → ИИ-ассистент» выберите другую модель из списка (например deepseek-v4.1-flash). Сообщение сервиса: %@", zh: "此模型与服务的对话协议不兼容 — 请在“设置 → AI 助手”中从列表选择其他模型（例如 deepseek-v4.1-flash）。服务消息：%@"),
        .init(en: "Invalid HTTP response", fa: "پاسخ HTTP نامعتبر بود", ru: "Недействительный HTTP-ответ", zh: "无效的 HTTP 响应"),
        .init(en: "Fetching the model list failed", fa: "دریافت فهرست مدل‌ها ناموفق بود", ru: "Не удалось получить список моделей", zh: "获取模型列表失败"),
        .init(en: "The response was not JSON", fa: "پاسخ JSON نبود", ru: "Ответ не является JSON", zh: "响应不是 JSON"),
        .init(en: "Is this useful for me?", fa: "به درد من می‌خورد؟", ru: "Это мне пригодится?", zh: "这对我有用吗？"),
        .init(en: "Given my profile, is this product/topic useful for me or not? Start with a one-line summary.", fa: "با توجه به پروفایل من، این محصول/موضوع به درد من می‌خورد یا نه؟ اول یک خط جمع‌بندی کن.", ru: "С учётом моего профиля, полезен ли мне этот продукт/тема? Начните с однострочного резюме.", zh: "根据我的画像，这个产品/主题对我有用吗？先用一行总结开头。"),
        .init(en: "5-point summary", fa: "خلاصهٔ ۵ نکته‌ای", ru: "Резюме из 5 пунктов", zh: "五点摘要"),
        .init(en: "Summarize this page in 5 short points; one sentence each.", fa: "متن این صفحه را در ۵ نکتهٔ کوتاه خلاصه کن؛ هر نکته یک جمله.", ru: "Резюмируй эту страницу в 5 коротких пунктах; по одному предложению на пункт.", zh: "用 5 个要点总结本页；每点一句话。"),
        .init(en: "Pros and Cons", fa: "مزایا و معایب", ru: "Плюсы и минусы", zh: "优点与缺点"),
        .init(en: "Write the pros and cons as two short lists and say which matters more for me.", fa: "مزایا و معایب این را دو فهرست کوتاه بنویس و بگو کدام برای من مهم‌تر است.", ru: "Напиши плюсы и минусы двумя короткими списками и скажи, что для меня важнее.", zh: "用两个简短列表写出优缺点，并说明哪个对我更重要。"),
        .init(en: "Risks and Downsides", fa: "ریسک‌ها و نکات منفی", ru: "Риски и недостатки", zh: "风险与缺点"),
        .init(en: "List the possible risks and downsides; mark any that are not mentioned on the page.", fa: "ریسک‌ها و نکات منفی احتمالی این را بنویس؛ هر کدام را اگر در صفحه نیامده مشخص کن.", ru: "Перечисли возможные риски и недостатки; отметь те, что не упомянуты на странице.", zh: "列出可能的风险与缺点；页面未提及的请标注出来。"),
        .init(en: "Compare with my needs and budget", fa: "مقایسه با نیاز و بودجهٔ من", ru: "Сравнение с моими потребностями и бюджетом", zh: "与我的需求和预算对比"),
        .init(en: "Compare this with my needs, expertise and budget and say whether it is worth paying for.", fa: "این را با نیاز، تخصص و بودجه‌ام مقایسه کن و بگو آیا ارزش پرداخت پول دارد یا نه.", ru: "Сравни это с моими потребностями, уровнем подготовки и бюджетом и скажи, стоит ли платить.", zh: "将它与我的需求、专业水平和预算对比，并说明是否值得花钱购买。"),
        .init(en: "Questions to ask before buying", fa: "سؤال‌های قبل از خرید", ru: "Вопросы перед покупкой", zh: "购买前要问的问题"),
        .init(en: "Write 5 questions I should ask the seller or maker before buying/using it.", fa: "۵ سؤال که قبل از خرید/استفاده باید از فروشنده یا سازنده بپرسم را بنویس.", ru: "Напиши 5 вопросов, которые мне стоит задать продавцу или производителю перед покупкой/использованием.", zh: "写出我在购买/使用前应问卖家或厂家的 5 个问题。"),
        .init(en: "The AI response was not readable even after one repair attempt: %@", fa: "پاسخ هوش مصنوعی حتی پس از یک تلاش ترمیم قابل‌خواندن نبود: %@", ru: "Ответ ИИ не удалось разобрать даже после одной попытки восстановления: %@", zh: "即使尝试修复一次后，AI 响应仍无法解析：%@"),
        .init(en: "The AI produced only a title or a map with too few nodes; the incomplete map was not saved. %@", fa: "هوش مصنوعی فقط عنوان یا ساختار کم‌گره ساخت؛ نقشهٔ ناقص ذخیره نشد. %@", ru: "ИИ создал только заголовок или карту со слишком малым числом узлов; неполная карта не сохранена. %@", zh: "AI 仅生成了标题或节点过少的导图；未保存不完整导图。%@"),
        .init(en: "Not enough structure could be derived from the page headings and paragraphs either.", fa: "از سرفصل‌ها و بندهای صفحه هم ساختار کافی به دست نیامد.", ru: "Из заголовков и абзацев страницы тоже не удалось получить достаточную структуру.", zh: "从页面标题和段落也无法获得足够的结构。"),
        .init(en: "The JSON was invalid and the fallback structure was not sufficient either.", fa: "JSON نامعتبر بود و ساختار جایگزین کافی نبود.", ru: "JSON недействителен, и резервной структуры тоже недостаточно.", zh: "JSON 无效，后备结构也不够充分。"),
        .init(en: "Technical: nodes=%d, rootChildren=%d, root='%@', branches='%@'", fa: "فنی: nodes=%d, rootChildren=%d, root='%@', branches='%@'", ru: "Технические сведения: nodes=%d, rootChildren=%d, root='%@', branches='%@'", zh: "技术信息：nodes=%d, rootChildren=%d, root='%@', branches='%@'"),
        .init(en: "The JSON could not be encoded as UTF-8.", fa: "JSON UTF-8 ساخته نشد.", ru: "Не удалось закодировать JSON в UTF-8.", zh: "无法将 JSON 编码为 UTF-8。"),
        .init(en: "Long content was summarized into a structured digest for the AI.", fa: "محتوای بلند برای هوش مصنوعی به digest ساختاریافته خلاصه شد.", ru: "Длинный контент был сведён в структурированный дайджест для ИИ.", zh: "长内容已汇总为结构化摘要供 AI 使用。"),
        .init(en: "The model's JSON response was not repairable; the structure was built from the page's own headings/paragraphs.", fa: "پاسخ JSON مدل قابل‌ترمیم نبود؛ ساختار از تیترها/بندهای خود صفحه ساخته شد.", ru: "JSON-ответ модели не удалось восстановить; структура построена из заголовков/абзацев самой страницы.", zh: "模型的 JSON 响应无法修复；结构由页面自身的标题/段落构建。"),
        .init(en: "The initial response was repaired.", fa: "پاسخ اولیه ترمیم شد.", ru: "Первоначальный ответ был восстановлен.", zh: "初始响应已修复。"),
        // ── ایمنی داده و بک‌آپ (رفع مشکلات فاز امنیتی) ──
        .init(en: "Storage Problem", fa: "مشکل ذخیره‌سازی", ru: "Проблема с хранилищем", zh: "存储问题"),
        .init(en: "Continue without saving", fa: "ادامه بدون ذخیره", ru: "Продолжить без сохранения", zh: "不保存继续"),
        .init(en: "Save failed: %@ — %@", fa: "ذخیره ناموفق بود: %@ — %@", ru: "Не удалось сохранить: %@ — %@", zh: "保存失败：%@ — %@"),
        .init(en: "Backups", fa: "بک‌آپ‌ها", ru: "Резервные копии", zh: "备份"),
        .init(en: "Back Up Now", fa: "بک‌آپ بگیر", ru: "Создать копию", zh: "立即备份"),
        .init(en: "Show Backups in Finder", fa: "نمایش بک‌آپ‌ها در Finder", ru: "Показать копии в Finder", zh: "在 Finder 中显示备份"),
        .init(en: "Backup created: %@", fa: "بک‌آپ ساخته شد: %@", ru: "Копия создана: %@", zh: "备份已创建：%@"),
        .init(en: "Backup failed: %@", fa: "بک‌آپ ناموفق بود: %@", ru: "Не удалось создать копию: %@", zh: "备份失败：%@"),
        .init(en: "A snapshot is taken automatically once a day; the last 5 automatic copies are kept (each a few hundred KB). Manual backups are never deleted.",
              fa: "روزی یک‌بار به‌صورت خودکار اسنپ‌شات گرفته می‌شود؛ ۵ نسخهٔ آخرِ خودکار نگه داشته می‌شوند (هرکدام چند صد کیلوبایت). بک‌آپ‌های دستی هرگز حذف نمی‌شوند.",
              ru: "Раз в день автоматически создаётся снимок; хранятся последние 5 автоматических копий (каждая — несколько сотен КБ). Ручные копии никогда не удаляются.",
              zh: "每天自动拍摄一次快照；保留最近 5 个自动副本（每个几百 KB）。手动备份不会被删除。"),
        .init(en: "Privacy note: when you use the assistant, the page's saved text, your profile and your question are sent to the assistant service above.",
              fa: "نکتهٔ حریم خصوصی: هنگام استفاده از دستیار، متن ذخیره‌شدهٔ صفحه، پروفایل شما و پرسشتان به سرویس دستیارِ بالا فرستاده می‌شود.",
              ru: "Заметка о приватности: при использовании ассистента сохранённый текст страницы, ваш профиль и ваш вопрос отправляются в указанный выше сервис ассистента.",
              zh: "隐私说明：使用助手时，页面的已存文本、您的画像和您的问题会发送到上方的助手服务。"),
        .init(en: "Reading List", fa: "خواندنی‌ها", ru: "Прочитать", zh: "稍后阅读"),
        .init(en: "Work", fa: "کاری", ru: "Работа", zh: "工作"),
        .init(en: "Entertainment", fa: "سرگرمی", ru: "Развлечения", zh: "娱乐"),
        .init(en: "Update", fa: "به‌روزرسانی", ru: "Обновление", zh: "更新"),
        .init(en: "Save Note", fa: "ذخیره یادداشت", ru: "Сохранить заметку", zh: "保存备注"),
        .init(en: "Folder Appearance", fa: "ظاهر پوشه", ru: "Внешний вид папки", zh: "文件夹外观"),
        .init(en: "Update Tags", fa: "به‌روزرسانی برچسب‌ها", ru: "Обновление тегов", zh: "更新标签"),
        .init(en: "Move to Folder", fa: "انتقال به پوشه", ru: "Переместить в папку", zh: "移动到文件夹"),
        // ── تمپلیت‌های ظاهری ──
        .init(en: "Classic", fa: "کلاسیک", ru: "Классическая", zh: "经典"),
        .init(en: "Midnight", fa: "نیمه‌شب", ru: "Полночь", zh: "午夜"),
        .init(en: "Theme", fa: "تمپلیت", ru: "Тема", zh: "主题"),
        .init(en: "The theme sets its own light/dark look; “Light Mode” applies to Classic only.",
              fa: "تمپلیت، حالت روشن/تاریک خودش را دارد؛ «حالت روشنایی» فقط روی «کلاسیک» اثر می‌گذارد.",
              ru: "Тема задаёт своё светлое/тёмное оформление; «Режим освещения» действует только для «Классической».",
              zh: "主题自带浅色/深色外观；「外观模式」仅对「经典」生效。"),
    ]
}
